[Feat/#127] : MixPanel 코드 삽입
ABloom-AOS/Merry_Android pull request #128
Opened 2024-05-26 13:40 UTC by leeugun123

#### close #127

### ✏️ 개요

MixPanel 코드 삽입 및 DatePicker 다크모드 코드 최적화

### 💻 작업 사항

MixPanel 코드 삽입 및 DatePicker 다크모드 코드 최적화

2024-05-27 01:43 UTC, kimyejoon commented
고생많으시네요 폴! 감사합니다 👏🏻

2024-05-27 04:29 UTC, ki960213 requested changes
mixpanel 처음 공부하느라 고생하셨을 것 같아요. 감사합니다 👍 
몇 가지 코멘트 남겼습니다. 확인해주세요 😊

2024-05-27 04:29 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/MixpanelManager.kt
> +    private var mixpanel: MixpanelAPI? = null
object가 아닌 class로 바꾸고 Hilt를 사용해서 context를 생성자로 받으면 `mixpanel` 멤버 변수의 타입을 non-null로 선언할 수 있을 것 같아요. 그러면 아래의 모든 함수에서 null 처리를 하지 않아도 될 것 같아요!
메모리 누수를 의도한다는 주석도 지울 수 있을 것 같아요.

2024-05-27 04:29 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/MixpanelManager.kt
> +    }
`getInstance`가 사용되는 곳을 보니 인스턴스를 얻기보단 mixpanel 멤버 변수를 초기화하는 목적으로 쓰이는 것 같아요. 멤버 변수를 생성 시점에 초기화한다면 `getInstance` 메서드는 없어도 될 것 같아요!

2024-05-27 04:29 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/MixpanelManager.kt
> +    }
`MixPanelManager` 객체의 메서드 명의 접미사로 `MixPanel`이 있는 게 좋을까요?

2024-05-27 04:29 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/home/LoginDialogFragment.kt
> +        MixpanelManager.setGoogleLoginMixPanel(googleToken)
`MixpanelManager` 클래스가 `object`가 아닌 `class`라도 `@Inject`를 이용해 객체를 사용할 수 있어요! Hilt의 기능이예요.

2024-05-27 04:29 UTC, ki960213 commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.BLUETOOTH" />
혹시 블루투스 권한을 사용하는 이유가 무엇인가요? 궁금해서 여쭤봅니다 ㅎㅎ

2024-05-28 04:19 UTC, leeugun123 commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.BLUETOOTH" />
https://github.com/mixpanel/mixpanel-android
이제보니 블루투스 퍼미션이 optional 이였군요.. 아무래도 실시간으로 협업하여 작업하다보니 
꼼꼼하게 읽어보지 못한 것 같습니다.
지금 당장 필요하지 않는 권한이기 때문에 지우겠습니다. 
하지만 추후 블루투스 관련 기능이 추가되면 다시 추가해야 될 것 같아요!
fb308dbc2ea3b95ae5076d89ea053f759ba19895

2024-05-28 04:19 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/MixpanelManager.kt
> +    private var mixpanel: MixpanelAPI? = null
495f04da5d81a19b39367ef5b2b5a4272e2dc987
별도의 Module을 생성하지 않고도 ApplicationContext를 생성자를 통해 직접 주입 받을 수 있었군요..
덕분에 새롭게 알게 됐습니다. 감사합니다!

2024-05-28 04:19 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/MixpanelManager.kt
> +    }
fd8c27a5cbc6b4dd3ce346b4595a4ecb54a369c6
MixPanelManager라는 네이밍에 이미 MixPanel 단어가 들어가 있기 때문에 메소드에도 
Mixpanel을 넣을 필요는 없을 것 같습니다. 수정했습니다!

2024-05-28 04:19 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/home/LoginDialogFragment.kt
> +        MixpanelManager.setGoogleLoginMixPanel(googleToken)
Hilt는 알면 알수록 객체간의 결합도를 정말 느슨하게 해준다는 것을 다시 상기시켜주네요. 
@Inject 어노테이션을 사용해서 수정하였습니다!

2024-05-28 04:54 UTC, ki960213 approved these changes
고생하셨습니다! 👍

2024-05-28 04:54 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/MeryApplication.kt
> +
불필요한 공백인 것 같아요 😢

2024-05-28 04:54 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/MixPanelModule.kt
> +}
굳이 모듈에 등록해야 할까요? `MixpanelAPI` 객체에 의존성이 있는 클래스는 `MixpanelManager` 밖에 없으니 `MixpanelManager` 클래스에서 직접 생성해도 괜찮지 않을까요?

2024-05-28 04:54 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/home/LoginDialogFragment.kt
> +        MixpanelManager.setGoogleLoginMixPanel(googleToken)
현재 위 코멘트의 @Inject 글자를 클릭하면 깃허브 유저의 프로필로 이동합니다. \`를 양 옆에 붙여서 `@Inject` 코드라는 것을 나타내면 좋을 것 같아요! 😊

2024-05-31 01:50 UTC, yoonchanchoi approved these changes
폴 고생하셨습니당
토마스 힐트 에러 수정 하시는거 보고 놀랐습니당^^

2024-06-08 13:32 UTC, merged