[Feat/#129]: 질문제작소에 바로가기 팝업추가
ABloom-AOS/Merry_Android pull request #130
Opened 2024-06-13 09:43 UTC by leeugun123

#### close #129

### ✏️ 개요

질문제작소에 바로가기 팝업추가

### 💻 작업 사항

질문제작소에 바로가기 팝업추가

### 📱결과 화면(optional)

리뷰어의 이해를 위해 스크린샷을 추가해주세요.

2024-06-14 05:59 UTC, ki960213 requested changes
전체적으로 코드가 많이 깔끔해서 리뷰하기 편했습니다 👍
몇 가지 코멘트 남겼으니 확인해주세요 ㅎㅎ

2024-06-14 05:59 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +    }
[질문제작소 팝업 명세](https://www.figma.com/design/QpwgpQK7hvlZ9hBcTVm8g7/[Android%2C-iOS]-MERY-2?node-id=5838-11554&t=UywAkYmj7jQY8tjv-0)를 보면 **close 버튼을 클릭했을 때만** 재활성화 되지 않도록 하고, 팝업 클릭 하여 질문제작소 웹뷰로 이동했을 때는 그렇지 않은 것 같아요! 질문제작소에 들어갔다가 실수로 뒤로 버튼을 클릭하면 다시 들어가고 싶을 것 같아요. :)

2024-06-14 05:59 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +    }
"팝업 다이얼로그를 딜레이와 함께 보여주다"라는 함수명이지만 진짜 하는 일은 **조건을 비교하여 다이얼로그를 보여줄지 말지 결정**하는 것이예요. 그래서 저라면 "showPopUpDialogIfNeed" 이런 식으로 조건부로 팝업 다이얼로그를 보여준다는 의미를 담아서 네이밍할 것 같아요!
그리고 보여줄지 말지 결정한 뒤 delay 함수를 실행하는 게 더 나을 것 같아요. 조건이 안맞으면 delay 함수도 실행될 필요가 없으니까요. 😊

2024-06-14 05:59 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +    }
이 함수의 이름이 "showPopupDialog"인 게 어울린다고 생각해요. 함수명이 동사로 시작한다는 점도 있구요ㅎㅎ

2024-06-14 05:59 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +    }
이 함수의 이름도 "hidePopupDialog"인 게 어울린다고 생각해요ㅎㅎ

2024-06-14 05:59 UTC, ki960213 commented on app/src/main/res/layout/fragment_category.xml
> +                android:importantForAccessibility="no"
혹시 ` android:importantForAccessibility="no"`의 의미를 아시나요?

2024-06-14 05:59 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/MainViewModel.kt
> +    var selectedQuestionFactory = false
앱 실행 동안 유지되어야 하는 상태를 `MainViewModel`에 잘 정의하셨군요! 👍 
해당 변수명도 [질문제작소 팝업 명세](https://www.figma.com/design/QpwgpQK7hvlZ9hBcTVm8g7/[Android%2C-iOS]-MERY-2?node-id=5838-11554&t=UywAkYmj7jQY8tjv-0)에 따라 `wasClosedQuestionFactoryPopup` 이런 식으로 네이밍하는 것이 어떨까요? 😄

2024-06-14 05:59 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +        mainViewModel.selectedQuestionFactory = true
문답을 작성하는 화면으로 이동할 때도 팝업을 닫을 필요는 없는 것 같아요 ㅎㅎ

2024-06-14 05:59 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
>              questionId
저도 최근에 코딩하면서 느낀건데, `selectQuestion` 메서드의 매개변수명이 `category`와 `questionId`인데 `category`의 인자를 정의하는 코드가 `categoryViewModel.category.value.name.lowercase()`처럼 `category`라는 것을 쉽게 알 수 없다면 매개변수 이름을 작성하는 것이 가독성이 더 좋다고 생각합니다 :)
따라서 저라면
```kotlin
mixpanelManager.selectQuestion(
    category = categoryViewModel.category.value.name.lowercase(),
    questionId = questionId
)
```
이렇게 작성할 것 같아요! 참고로 저는 코틀린의 매개변수 명을 작성하도록 바꾸는 단축키를 설정해놨어요!

2024-06-14 05:59 UTC, ki960213 commented on app/src/main/res/layout/fragment_category.xml
> +            app:layout_constraintTop_toTopOf="@+id/make_question_pop_up_dialog" />
질문제작소 팝업을 xml에서 invisible로 설정한다면 다른 화면으로 이동하면 항상 팝업이 사라져있을 거예요. 다른 화면으로 이동하면 뷰가 모두 사라지고 뒤로 가기 버튼으로 다시 되돌아오면 뷰를 다시 생성하기 때문이예요.
팝업의 가시성 상태를 뷰모델에서 유지하고 있다면 그렇지 않을 거예요!

2024-06-14 10:01 UTC, leeugun123 commented
상세하게 코멘트 주셔서 정말 감사합니다. 토마스! 
네이밍 관련해서 저도 정말 고민이 많았는데 아무래도 많이 공부하고 연습해야 될 것 같아요!

2024-06-14 10:43 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +    }
명세서를 자세히 읽어보니 팝업창이 닫는 조건이 Close 버튼을 눌렀을때만 이였군요!
확인해주셔서 감사합니다.
0525374911251aec253ceb8b25cbbfb57629e017

2024-06-14 10:43 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/MainViewModel.kt
> +    var selectedQuestionFactory = false
제시 해주신 변수명이 좀더 적절한 것 같아요! 
594297b2487adbded072da1c22852e8a931ec30b

2024-06-14 10:43 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +        mainViewModel.selectedQuestionFactory = true
이 부분에 관해서는 Hand-off 과정에서 벤틀리랑 이야기 했는데 문답 작성 화면으로 이동한 경우, 사용자가 원하는 질문을 찾았다고 판단하여 팝업창이 다시 뜨지 않는 걸로 결정했습니다. 하지만 추후 다시 IOS 개발자분들과 PM 분들이랑 다시 이야기 해서 수정해야 될 것 같아요!

2024-06-14 10:43 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +    }
확실히 메소드 역할에 맞는 네이밍이 정말 중요한 것 같아요! 토마스가 제시해주신대로 메소드명은 수정했습니다.
0d9daff4bec9d38165a0358c652571681156e7de

그리고 저도 처음에 토마스가 말씀해주신 로직대로 코드를 작성했는데 비로그인시에 팝업창이 뜨는 오류를 해결하다가
처음 로그인을 확인하는 초기값이 true로 설정되어 딜레이 없이 checkPopUpDialogCondition()을 실행하면 자동으로 로그인 값이 true로 판별되어 팝업창이 뜨더라고요ㅠㅠ 혹시 더 좋은 방법이 있을까요?

2024-06-14 10:43 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +    }
아 이거는 제가 좀 더 고민해서 네이밍 했어야 하는데..ㅠㅠ  급하게 네이밍 했네요! 피드백 주셔서 감사합니다.
c71b91e2c753e99aa5745c633f1c081abd42c78c

2024-06-14 10:43 UTC, leeugun123 commented on app/src/main/res/layout/fragment_category.xml
> +                android:importantForAccessibility="no"
android:importantAccessibility="no"은 ImageView에 대해서 Voice Assistant를 받지 않는 걸로 알고 있습니다.
보통은 contentDesciption을 사용하여 시각장애인분들에게 ImageView에 대한 정보 제공을 위해서가 맞을까요?
이 부분에 대해서 나중에 토마스에게 여쭤볼려고 했는데 코드 리뷰 통해서 문의 드릴 수 있어서 좋네요. ㅎㅎ

2024-06-14 10:43 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
>              questionId
lowercase()를 실행한 이유는 믹스패널 서버 부분에서 카테고리를 소문자만 인식하는 걸로 설정되어 있어
lowercase()를 통해 대문자로 된 카테고리 String를 소문자로 변형 했었습니다. 하지만 이럴 경우, 다른 개발자 분이
코드 로직을 파악할때 매개변수명이 무엇인지 판별하기가 어려운 이슈가 생겨나네요..
토마스가 말씀해주신대로 매개변수명을 명시하니 가독성이 훨씬 좋은 것 같습니다. 새롭게 배워가네요!

27564e977e946de1b25498411619b7809ac54518

2024-06-14 11:28 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +    }
그러네요ㅠㅠ 정확히 하려면 `isLogin`의 초기값을 `LoginUserUiState.Loading`와 같은 sealed class로 로딩하는 중이라는 상태를 정의하고(혹은 로딩 중이라는 상태를 나타내기 위해 nullable로 선언. 이 방법은 로딩 중이라는 상태가 null로 명시되기 때문에 직관적이지 않음), 로딩 상태는 무시하고 이후의 로그인 여부를 나타내는 상태를 관찰하도록 구현해야 할 것 같아요. 하지만 기존 코드대로 해도 크게 문제가 없을 것 같아요! 이 부분은 폴의 생각대로 구현해주세요 😊

2024-06-14 11:31 UTC, ki960213 commented on app/src/main/res/layout/fragment_category.xml
> +                android:importantForAccessibility="no"
잘 알고 계시는군요 👍

2024-06-14 11:34 UTC, ki960213 commented on app/src/main/res/layout/fragment_category.xml
> +                android:importantForAccessibility="no"
잘 알고 계시는 것 같아요 👍 저도 시간 없을 땐 전부 `android:importantForAccessibility="no"`를 사용합니다. 😆 
위 이미지 뷰도 `android:importantForAccessibility="no"`가 적절한 것 같아요.

2024-06-14 11:36 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +        mainViewModel.selectedQuestionFactory = true
오 그러네요 ㅎㅎ 문답 작성 화면으로 이동했다면 팝업창을 보여줄 필요가 없는 것 같네요!

2024-06-14 11:47 UTC, ki960213 approved these changes
고생하셨습니다 👍 
간단한 코멘트 남겼습니다. 간단한 거라서 바로 approve 했습니다 ㅎㅎ

2024-06-14 11:47 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +        categoryViewModel.isLogin.value && !mainViewModel.wasClosedQuestionFactoryPopup
이전 코드리뷰에서 놓친 부분이예요 😢 
보통 코틀린에서 상태가 유효한지 검증하기 위해 `check` 함수를 사용합니다.([참고자료](https://velog.io/@eastperson/Kotlin%EC%9D%98-check%EC%99%80-require-ibg71b1z))
`check` 함수를 사용하는 이유는 개발자가 의도한 대로 코드를 작성했는지 확인하기 위함입니다. `require`도 마찬가지구요.ㅎㅎ
저는 위처럼 `Boolean` 타입의 값을 반환하는 함수의 이름은 "is~" 혹은 전의 예시처럼 "was~" 이런 식으로 be동사 혹은 조동사를 앞에 붙여 의문문과 비슷하게 네이밍하는 것을 선호합니다. 영어에서도 be동사나 조동사로 시작하는 의문문의 대답은 Yes 혹은 No로 대답하니까요.([참고자료](https://blog.naver.com/eng1588/222401314592)) 😄

2024-06-14 11:57 UTC, leeugun123 commented on app/src/main/res/layout/fragment_category.xml
> +            app:layout_constraintTop_toTopOf="@+id/make_question_pop_up_dialog" />
327ffe96d83622972b17792e68f2bfed0db51be6
말씀하신대로 categoryViewModel의 변수를 추가하여 팝업의 visibility를 설정했습니다. 하지만 토마스가 말씀하신 의도대로
했는지 잘 모르겠습니다. ㅠㅠ 한번 확인해주시면 감사하겠습니다.

2024-06-14 12:23 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +        categoryViewModel.isLogin.value && !mainViewModel.wasClosedQuestionFactoryPopup
전체적으로 제가 만든 메소드 네이밍을 살펴보니 무언가 확인할때 주로 check로 네이밍 한 경우가 많았네요.
무언가 확인하는 메소드 네이밍 시 토마스가 말씀하신 것처럼 is로 시작하여 네이밍 하는 것이협업할때 
코드 가독성을 더 높여준다고 생각합니다. 

a80d8eba7f29c46059c5c375ded5d8a2c9691685
d2a181411636462155b881334839bb6511ebc1f6

2024-06-14 12:35 UTC, ki960213 requested changes
간단한 코멘트 남겼습니다 ㅎㅎ

2024-06-14 12:35 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +    }
이렇게 간단한 코드는 저는 함수 분리를 하지 않는 편입니다. 함수 분리의 목적은 **복잡한 로직의 추상화**와 **재사용**이라고 생각합니다. 함수 분리를 남용하면 실제 구현 코드를 보기 위해 탐색 과정이 늘어나서 필요할 때만 사용하는 편입니다. 😊

2024-06-14 12:35 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +        hidePopupDialog()
`closePopUpDialog` 함수를 호출하면 될 것 같아요!

2024-06-14 12:44 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +    }
categoryViewModel.isPopupVisible.value = true 이 코드만으로 팝업창이 보여진다는 것을 쉽게 알 수 있기 때문에
함수 분리는 불필요하겠네요!
4af64145f4b993251c222ac6017e6dab689a7659

2024-06-14 12:44 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +        hidePopupDialog()
앗! 찾아주셔서 감사합니다.
4af64145f4b993251c222ac6017e6dab689a7659

2024-06-15 04:33 UTC, ki960213 commented on app/src/main/res/layout/fragment_category.xml
> +            app:layout_constraintTop_toTopOf="@+id/make_question_pop_up_dialog" />
`app:is_visible="@{viewModel.isPopupVisible()}"`에서 소괄호는 없어도 괜찮습니다 ㅎㅎ

2024-06-15 14:13 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
>      private fun setupDataBinding() {
최근에 고민이 될만한 코드 스타일을 보았습니다.
Ex) 
```
private fun setupDataBinding() = whit(binding){
binding.viewModel = categoryViewModel
        onUpButtonClick = { findNavController().popBackStack() }
        onLoginButtonClick = ::handleLoginButtonClick
        onNavigateQuestionFactoryButtonClick = ::navigateToQuestionFactoryWebView
        onPopUpDialogCloseButtonClick = ::closePopUpDialog
}
```
이런식의 with로 묶어주는 코드를 본적인 있는데 해당 코드에 대해서 다들 어떻게 생각하시는지 궁금합니다.
전 개인적으로 binding 붙이는게 좋다고 생각하시는데 특정 회사에서 이렇게 쓴다고 하더라고용 
개인적으로 궁금해서 질문했습니당^^

2024-06-15 17:27 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_category.xml
> +                android:importantForAccessibility="no"
생각 못했는데 언제부터인가 보이기 시작하더라고^^
찾아보니 4.1 젤리 빈 부터라고 하네용

2024-06-15 17:43 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/MainViewModel.kt
> +    var selectedQuestionFactory = false
저도 제시 해주신 변수명이 좋은거 같아용~~!

2024-06-15 18:38 UTC, yoonchanchoi approved these changes
구현하시느라 고생하셨어용

2024-06-16 11:29 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
>      private fun setupDataBinding() {
자주 사용되는  binding을 공통으로 묶어서 메소드의 가독성을 높이는 방법도 좋은 것 같습니다. 한번 참고해서 나중 PR때 구현해볼게요!

2024-06-16 12:29 UTC, merged

2024-06-16 12:36 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
>      private fun setupDataBinding() {
수신 객체를 바인딩 객체로 제한함으로써 `setupDataBinding()` 함수가 바인딩 객체를 초기화하는 일만 하도록 하기가 더 쉬워질 것 같아요. 즉, 함수가 이름에 비해 너무 많은 일을 하고 있다는 것을 쉽게 알 수 있을 것 같아요. 👍 

위에서 수신 객체란 말을 쓴 이유는 객체 지향 프로그래밍에서 어떤 객체의 프로퍼티(사실 자바에서는 메서드 호출임)나 메서드를 호출하는 것은 "해당 객체에게 메세지를 보내면 객체가 메세지를 수신하고 결과를 반환하는 것"을 의미하기 때문입니다. 😄