Feature/13 카카오로그인 및 로그인 UI 구현
ABloom-AOS/Merry_Android pull request #16
Opened 2024-03-18 06:47 UTC by leeugun123

#### close #13

### ✏️ 개요

카카오로그인 및 로그인 UI 구현

### 💻 작업 사항

BottomDialogFragment 카카오 로그인 구현
HomeActivity 생성 및 BottomDialogFragment 적용
BottomDialogFragment UI XML 구성
 
+ 앱 상단바 제거 및 패키지명 수정에 따른 Manifest 라벨 변경

### 📱결과 화면(optional)

![KakaoTalk_Photo_2024-03-18-15-41-26](https://github.com/abloom-AOS/MERY_Android/assets/50404123/ea172c7a-377e-480d-a741-9b0f7661c24a)

### 📚 ETC(optional)

아마 로그인 UI XML 부분에서 많은 리뷰가 필요 할 것 같습니다.

2024-03-18 07:32 UTC, kimyejoon commented
확인했습니다! 현재 카카오 로그인은 UI만 구현되어 있는 상태인것인지 궁금합니다 😲

2024-03-18 07:38 UTC, leeugun123 commented
> 확인했습니다! 현재 카카오 로그인은 UI만 구현되어 있는 상태인것인지 궁금합니다 😲

기능까지 구현 완료했습니다. 다만 디자인 부분은 개발자분들의 리뷰에 따라 별도의 수정이 필요 할 것 같습니다.

2024-03-18 13:55 UTC, ki960213 reviewed
약간 코멘트가 많을 수 있지만 하나하나 배워나간다면 금방 실력이 늘 수 있을거라 생각해요 👍

2024-03-18 13:55 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/HomeActivity.kt
> +    }
아직 불필요한 공백이 있는 걸 보니 코드 전체 정렬을 하지 않고 푸시한 것 같아요.
커밋하기 전에 코드 정렬을 해준다면 매 커밋마다 정렬된 코드를 볼 수 있을 것 같아요.
처음이라 익숙하지 않은 점 이해합니다. 저도 처음에 많이 까먹었습니다 😊

2024-03-18 13:55 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/HomeActivity.kt
> +        bottomSheetFragment.setStyle(DialogFragment.STYLE_NORMAL , R.style.AppBottomSheetDialogTheme)
로그인 다이얼로그의 스타일은 `LoginDialogFragment` 클래스에서 설정하는 게 어떨까요? 그렇게 하지 않으면 만약 로그인 다이얼로그를 재사용할 때 어떤 일이 발생할까요?

2024-03-18 13:55 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/HomeActivity.kt
> +    }
함수 분리 잘 해주셨네요 👍

2024-03-18 13:55 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
> +        * */
주석에 TODO를 포함한다면 이후에 해야할 일을 찾기 더 쉬울 것 같아요. 검색해서 찾을 수 있으니까요.

```kotlin
// TODO("화면 이동 로직 구현")
// 파이어베이스를 조회하여 기존 회원이 아닌 경우 회원가입 화면으로 이동한다.
```

2024-03-18 13:55 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
> +        }
`apply`같은 수신 객체 지정 람다를 사용하면 장점이 무엇일까요?

그 장점이 이 코드에서 드러났을까요?

2024-03-18 13:55 UTC, ki960213 commented on app/src/main/res/layout/fragment_login_dialog.xml
> +    </RelativeLayout>
`RelativeLayout` 대신 `ConstraintLayout`을 사용하면 어떨까요? 그리고 모든 레이아웃과 위젯의 크기를 하드코딩하셨네요 😢 `RelativeLayout`의 상위호환인 `ConstraintLayout`을 사용하여 유지보수하기 쉽게 작성하면 좋을 것 같아요. `ConstraintLayout`은 Design 툴을 사용하여 더 쉽게 뷰를 구현할 수도 있어요.

`ConstraintLayout` 참고 자료: https://developer.android.com/develop/ui/views/layout/constraint-layout?hl=ko

2024-03-18 13:55 UTC, ki960213 commented on app/src/main/res/drawable/rounded_top_corners.xml
> +        />
radius를 30dp로 설정한 이유가 무엇인지 궁금합니다. 피그마에는 12dp로 나와있어요. 😢 
![image](https://github.com/abloom-AOS/MERY_Android/assets/123928686/2ff0745b-84ac-4371-8080-1e30fc9f9e82)

2024-03-18 13:55 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
> +    }
임시로 정한 문자열인가요? ❓

2024-03-18 13:55 UTC, ki960213 commented on app/src/main/res/values/themes.xml
> +    <style name="Base.Theme.Mery" parent="Theme.AppCompat.DayNight.DarkActionBar">
NoActionBar에서 DarkActionBar로 바꾸신 이유가 궁금합니다...!

2024-03-18 13:55 UTC, ki960213 commented on app/src/main/res/values/themes.xml
> +    </style>
login_text_style은 로그인 화면에서만 쓰이므로 공통적인 테마를 설정하는 `themes.xml` 파일에는 두지 않는 게 좋아보여요 😊

2024-03-18 13:55 UTC, ki960213 commented on app/src/main/res/layout/fragment_login_dialog.xml
> +                />
지금보니 기존에 정해진 텍스트 스타일을 사용하면 글자가 이상하게 표시되는군요. 바꾸겠습니다 😓

2024-03-18 13:55 UTC, ki960213 commented on app/src/main/res/layout/fragment_login_dialog.xml
> +            android:background="@drawable/kakao_login_medium_wide" />
이미지 버튼 대신 카카오톡 아이콘과 background를 따로 설정하여 구현하면 다양한 너비의 기기에도 버튼의 모양이 깨지지 않을 것 같아요.

2024-03-18 13:55 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
> +    private fun bindingSet() {
해당 함수는 카카오 로그인 버튼을 클릭했을 때 무슨 일을 수행하는지 초기화해주고 있어요.
그 의미가 잘 드러나게 `setupKakaoLoginButton()` 같은 식으로 정하면 어떨까요?
저는 주로 뷰를 초기화할  때 `setupXxx()` 네이밍을 사용해요.
그리고 대부분 함수는 동사로 시작하도록 네이밍합니다. 함수를 사용한다는 것은 어떤 로직을 실행하도록 명령하는 것이기 때문이죠.

[해당 링크](https://medium.com/mj-studio/%EC%BD%94%ED%8B%80%EB%A6%B0-%EC%9D%B4%EB%A0%87%EA%B2%8C-%EC%9E%91%EC%84%B1%ED%95%98%EC%8B%9C%EB%A9%B4-%EB%90%A9%EB%8B%88%EB%8B%A4-94871a1fa646)를 참고해주세요. 😄

2024-03-19 06:49 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
> +    companion object{
해당 부분을 companion Object로 불변성 해주신 부분 너무 좋은거 같습니다. 

추후 코드를 합치구 수정하는 부분에서 Constants 클래스 파일을 만들어 한꺼번에 관리하고 싶습니다. 
괜찮을까용?

2024-03-19 06:50 UTC, leeugun123 commented on app/src/main/res/values/themes.xml
> +    <style name="Base.Theme.Mery" parent="Theme.AppCompat.DayNight.DarkActionBar">
NoActionBar로 적용 할 경우, 버튼 색깔 변경 시 적용이 안돼서 DarkActionBar로 변경하였습니다.

2024-03-19 06:50 UTC, leeugun123 commented on app/src/main/res/drawable/rounded_top_corners.xml
> +        />
피그마 상에 Radius 있는 부분이 px로 나와 있어서 이를 dp로 처리해야하는지 의문이 생겨서 임시로 처리 한 것 같습니다.
혹시 피그마 상에 px와 dp를 같은 개념으로 두고 개발하면 되는 것인지 궁금합니다.
+ 일단 토마스가 말한 것처럼 30dp로 수정하였습니다!

34ee73d37a099c145a924ca44071806e1aca014a

2024-03-19 06:50 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
> +    }
네 일단은 임시로 정해두었고, 카카오 로그인 실패 시 오류처리를 위해 문자열로 남겨두었습니다.
만약 필요하지 않는 문자열 이라고 생각되시면 수정하겠습니다!

2024-03-19 06:50 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
> +        * */
아 TODO가 있었네요. 다음 PR때는 파이어베이스 연동 등 임시의 작업을 주석처리시 TODO를 이용해서 주석 처리 하겠습니다.

2024-03-19 06:50 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/HomeActivity.kt
> +    }
아 사실은 merge 후 코드 정렬을 수행하려 하였는데 토마스가 말씀하신 것처럼 정렬 후, PR을 해야 코드리뷰 하는 입장에서 
더 수월하게 진행 될 것 같습니다.

2024-03-19 06:50 UTC, leeugun123 commented on app/src/main/res/values/themes.xml
> +    </style>
생각해보니 자주 사용하는 부분만 Style에 적용하는 것이 좋은 것 같습니다. 즉시 수정하겠습니다.

2024-03-19 06:50 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/HomeActivity.kt
> +        bottomSheetFragment.setStyle(DialogFragment.STYLE_NORMAL , R.style.AppBottomSheetDialogTheme)
재사용 할때마다 불필요한 오버헤드가 생길 것 같습니다. 수정하겠습니다!

2024-03-19 06:50 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
> +        }
여러개의 뷰를 사용할때는 효과적이지만 지금은 카카오로그인 버튼 1개 밖에 View가 존재 하지 않으므로 비효율적인 것 같습니다. 수정하겠습니다!

2024-03-19 06:50 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
> +    private fun bindingSet() {
좋은 링크와 정보 감사합니다. 앞으로 메소드 이름 지을때 좀 더 주의해서 만들겠습니다. 

a221323b075e45680fdb97c67dbcfe2a643d25b5

2024-03-19 06:50 UTC, leeugun123 commented on app/src/main/res/layout/fragment_login_dialog.xml
> +    </RelativeLayout>
좋은 정보 감사합니다. ConstraintLayout으로 변경하여 수정하겠습니다!

034b7fe450b3aa30dd8cbdbab4f87337164e3044

2024-03-19 06:50 UTC, leeugun123 commented on app/src/main/res/values/themes.xml
> +    <style name="Base.Theme.Mery" parent="Theme.AppCompat.DayNight.DarkActionBar">
NoActionBar로 다시 수정하였습니다. Button은 android.widget.Button로 구현하니 색상 변경 시 잘 적용됩니다.

2024-03-19 06:50 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/HomeActivity.kt
> +    }
코드 정렬 해서 다시 PR 올렸습니다!

2024-03-19 06:50 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/HomeActivity.kt
> +        bottomSheetFragment.setStyle(DialogFragment.STYLE_NORMAL , R.style.AppBottomSheetDialogTheme)
4c47fc79609cd8bdd0e8e287ae1d0c07e36be36f

2024-03-19 06:50 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
> +        * */
d9ac10923b18bcb6b931e0d8b94990076ce16202

2024-03-19 06:50 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
> +        }
a221323b075e45680fdb97c67dbcfe2a643d25b5

2024-03-19 06:50 UTC, leeugun123 commented on app/src/main/res/values/themes.xml
> +    </style>
9ff45e98dd155a4e78de8656882733157702d987

2024-03-19 06:50 UTC, leeugun123 commented on app/src/main/res/layout/fragment_login_dialog.xml
> +            android:background="@drawable/kakao_login_medium_wide" />
5df977f95019629a5baffad6b61ee97c8707e1a5

2024-03-19 06:50 UTC, leeugun123 commented on app/src/main/res/layout/fragment_login_dialog.xml
> +            android:background="@drawable/kakao_login_medium_wide" />
추가적으로 카카오 아이콘을 어떻게 Button에 적용해야하는지 잘 모르겠습니다. 제 역량 부족인 것 같습니다.
리뷰 후 어떻게 구현해야 하는지 피드백 주시면 정말 감사하겠습니다.

2024-03-19 06:53 UTC, yoonchanchoi approved these changes

2024-03-19 07:02 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
> +    companion object{
일단 지금은 클래스가 많지 않으니  companion Object로 작성하였고 오른이 말씀하신것처럼 추후에 Constants 클래스 파일을 만들어 한꺼번에 관리하는 것이 좋을 것 같습니다.

2024-03-19 07:10 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
> +        }
코틀린의 수신 객체 지정 람다의 존재 목적은 가독성을 위한 것입니다. 저는 여러 개의 뷰를 사용할 때도 apply를 사용하지 않을 것 같아요. `binding` 코드를 덜 작성하는 게 가독성을 향상한다고 생각하지 않거든요. 오히려 코드의 depth가 늘어나서 보기 안 좋을 것 같아요.

각 수신 객체 지정 람다를 언제 사용하면 좋을지 찾아보면 좋을 것 같아요

2024-03-19 07:13 UTC, ki960213 commented on app/src/main/res/drawable/rounded_top_corners.xml
> +        />
네 dp로 생각하고 개발하면 됩니당.

2024-03-19 07:14 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
> +    }
만약 정식으로 사용할 문자열이라면 string resource로 추가하는 게 좋을 것 같아요. 안드로이드에서 resource를 사용하는 목적을 알면 그 이유를 알 수 있어요.

2024-03-19 07:15 UTC, ki960213 commented on app/src/main/res/values/themes.xml
> +    <style name="Base.Theme.Mery" parent="Theme.AppCompat.DayNight.DarkActionBar">
버튼의 색상을 변경하기 위해 테마를 변경하는 건 올바른 문제 해결이 아닙니다. 만약 테마에 영향 받지 않는 버튼을 만들고 싶다면 저라면 Button 대신 다른 뷰를 사용할 것 같아요.

2024-03-19 07:16 UTC, ki960213 commented on app/src/main/res/values/themes.xml
> +    </style>
이미 정의된 text style 리소스를 사용하면 유지보수하기 더 쉬울 것 같아요. 스타일 변경에 따라 앱 전체의 스타일이 달라질 수 있으니까요 😊

2024-03-19 07:18 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
> +    companion object{
상수는 상수가 사용될 코드와 가까이 있는 게 코드의 응집도가 높다고 생각합니다. 따라서 Constants 클래스를 만드는 것은 좋지 않다고 생각합니다.   
혹시 상수를 한 곳에 묶으려는 이유가 뭔지 알려주실 수 있나요?

2024-03-19 07:54 UTC, kimyejoon commented on app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
> +        * */
주석에 TODO 를 다는 방식으로 컨벤션을 맞추신다면, @yoonchanchoi 오른도 함께 보시면 좋을 것 같아 멘션 남깁니다 !

2024-03-19 07:57 UTC, kimyejoon commented on app/src/main/res/drawable/rounded_top_corners.xml
> +        />
<img width="845" alt="image" src="https://github.com/abloom-AOS/MERY_Android/assets/76995471/aff4ca6c-d80b-4638-99ae-f53ee22ef35e">

피그마에서 Dev 모드를 켜시고 보시면 정확한 dp 값을 아실 수 있을 거예요!

@leeugun123 @ki960213

2024-03-19 13:10 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
> +        }
코드의 가독성을 위해서는 apply를 적용하는 것이 무조건 좋다고 생각했는데(물론 좋을 때도 있지만)
토마스 이야기를 들어보니 상황에 따라 유연하게 코드를 작성해야 한다는 것을 배우게 되었네요..!!
중요한 것은 코드의 유지보수성과 가독성을 높이는 것이 목표니까요!!

2024-03-19 13:16 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
> +    companion object{
상수를 한 곳에 묶어서 사용하면 용이하다고 생각 되었는데  토마스의 피드백을 통해 코드 응집도에 대한 개념을 공부하니
모듈이나 클래스를 설계할 때 관련된 요소들을 함께 묶어야 관리가 더 용이 할 것 같습니다.

2024-03-19 14:03 UTC, leeugun123 commented on app/src/main/res/values/themes.xml
> +    <style name="Base.Theme.Mery" parent="Theme.AppCompat.DayNight.DarkActionBar">
Button 대신 Constraintlayout으로 변경하였습니다.
d91f05b1aa18bd3c31153f663716dd3e699a7a27

2024-03-19 14:04 UTC, leeugun123 commented on app/src/main/res/layout/fragment_login_dialog.xml
> +            android:background="@drawable/kakao_login_medium_wide" />
오른과 토마스 덕분에 해결했습니다. 정말 감사합니다.
d91f05b1aa18bd3c31153f663716dd3e699a7a27

2024-03-19 14:11 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
> +    companion object{
저도  그게 좋다고 생각됩니다. 만약 수정할 일이 있더라도 해당 클래스에 관련된 요소만 수정하면되는데 만약 Constants로 통합해서 묶게되면 나중에 수정사항 때 충돌나기도 쉽고 수정하는데도 힘들거 같습니다.!!

2024-03-19 14:16 UTC, ki960213 requested changes
몇 가지 코멘트 남겼습니당. 확인해주세요 😊

2024-03-19 14:16 UTC, ki960213 commented on app/src/main/res/layout/activity_home.xml
> +        android:background="#F5F1F6"
디자인 시스템에 정의된 색상을 이용해주세요 😊

2024-03-19 14:16 UTC, ki960213 commented on app/src/main/res/layout/fragment_login_dialog.xml
> +                android:textSize="28sp"
디자인 시스템에 정의된 색상과 텍스트 스타일을 적용해도 좋을 것 같아요.

2024-03-19 14:16 UTC, ki960213 commented on app/src/main/res/layout/fragment_login_dialog.xml
> +            app:layout_constraintStart_toStartOf="parent"
로그인 다이얼로그의 모든 요소가 부모로부터 좌우 마진이 20dp예요.   
부모 뷰에 수평 패딩을 설정하면 자식 뷰는 마진을 설정하지 않아도 되지 않을까요?

2024-03-19 14:17 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
> +        }
저도 보통 apply를 많이 사용하는 경우가 있는데 많은 양의 요소를 적용하는 경우가 아니면 피해야겠습니다.

2024-03-19 14:22 UTC, leeugun123 commented on app/src/main/res/layout/activity_home.xml
> +        android:background="#F5F1F6"
#F5F1F6가 현재 Color 폴더에 없는 상태인데 따로 추가해서 적용해야 하나요?

2024-03-19 14:28 UTC, ki960213 commented on app/src/main/res/layout/activity_home.xml
> +        android:background="#F5F1F6"
그러네요;; 흠... 일단은 따로 추가해야 할 것 같네요 😓 내일 디자이너 분께 한 번 말해보겠습니다

2024-03-19 14:44 UTC, leeugun123 commented on app/src/main/res/layout/fragment_login_dialog.xml
> +            app:layout_constraintStart_toStartOf="parent"
저도 그렇게 생각해서 최상위 부모뷰인 Constraintlayout에 마진을 설정하고 앱을 실행하니 적용되지가 않습니다.
지금 방법은 찾아보고 있는데 왜 적용이 안되는지 잘 모르겠네요.

2024-03-19 15:09 UTC, leeugun123 commented on app/src/main/res/layout/fragment_login_dialog.xml
> +                android:textSize="28sp"
1c4577e71b706c5fedae3814a81676556733cb20 
수정했습니다. 색상과 텍스트 스타일을 알맞게 적용항였는지 확인해주시면 감사하겠습니다.

2024-03-19 15:10 UTC, leeugun123 commented on app/src/main/res/layout/fragment_login_dialog.xml
> +            app:layout_constraintStart_toStartOf="parent"
1148e7cca4f0d5e671e73c6ee70b2b1aa87e8ba1

최상위 뷰에서 padding 적용하여 수정하였습니다.

2024-03-19 15:30 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
> +    }
eefaaf5688f95d39db4e02cd6c1137e8757fe22a

string resource에 넣고 추가하여 적용하였습니다. 해당 commit 확인해주시고 피드백 주시면 감사하겠습니다.

2024-03-19 15:56 UTC, ki960213 commented on app/src/main/res/layout/fragment_login_dialog.xml
> +                android:textSize="28sp"
피그마에는 로그인 텍스트의 fontWeight가 700이네요.   
`android:textStyle="bold"`로 굵게 해주세용. 이거 쓰면 자동으로 700으로 맞춰집니다.

2024-03-19 15:59 UTC, ki960213 requested changes
간단한 코멘트 남겼습니다. 확인 부탁드려요~

2024-03-19 15:59 UTC, ki960213 commented on app/src/main/res/layout/fragment_login_dialog.xml
> +                app:layout_constraintTop_toTopOf="parent" />
피그마 대로 굵게 바꿔주시면 감사하겠습니다. 😊

2024-03-19 15:59 UTC, ki960213 commented on app/src/main/res/layout/fragment_login_dialog.xml
> +                app:layout_constraintTop_toTopOf="parent" />
불필요한 속성은 지워주세용

2024-03-20 04:48 UTC, leeugun123 commented on app/src/main/res/layout/fragment_login_dialog.xml
> +                app:layout_constraintTop_toTopOf="parent" />
79f1bb4b9c54e3ee0e5372f77414f3ffcfbe7476

불필요한 속성 제거했습니다!

2024-03-20 04:48 UTC, leeugun123 commented on app/src/main/res/layout/fragment_login_dialog.xml
> +                app:layout_constraintTop_toTopOf="parent" />
d515358bbfa355b26bd7ad1b7daf709f24d43741 

textStyle을 bold로 설정하여 수정하였습니다!

2024-03-20 04:49 UTC, leeugun123 commented on app/src/main/res/layout/fragment_login_dialog.xml
> +                android:textSize="28sp"
d515358bbfa355b26bd7ad1b7daf709f24d43741 
수정하였습니다!

2024-03-20 05:12 UTC, ki960213 requested changes
마지막으로 부탁드립니다 😊

2024-03-20 05:12 UTC, ki960213 commented on app/src/main/res/layout/fragment_login_dialog.xml
> +                app:layout_constraintTop_toBottomOf="@id/loginText" />
필요한 속성까지 제거했네요 😢 
ConstraintLayout을 사용할 때 수평 제약조건과 수직 제약조건은 필수로 정의해야 합니다. 제가 생각한 불필요한 속성은 bias입니다. 어차피 가운데에 있기 때문에 bias를 설정할 필요가 없습니다.

2024-03-20 05:30 UTC, leeugun123 commented on app/src/main/res/layout/fragment_login_dialog.xml
> +                app:layout_constraintTop_toBottomOf="@id/loginText" />
e323041d30057c1f2167d4a0160bbddf8e7e5da8
아 bias를 제거하는 말씀이셨군요..

제약조건 자체가 이미 가운데 있기 때문에 bias 자체를 설정할 필요가 없었네요.. 또 한번 배워갑니다!

2024-03-20 05:37 UTC, ki960213 approved these changes
간단한 것이므로 제가 변경 후 푸시하겠습니다.

2024-03-20 05:37 UTC, ki960213 commented on app/src/main/res/layout/fragment_login_dialog.xml
> +            android:layout_marginTop="16dp"
![image](https://github.com/abloom-AOS/MERY_Android/assets/123928686/b52f4ae5-fd68-4cdf-af9a-d7334cd2ed1f)

디자인대로 구현해주시면 감사하겠습니다. marginTop이 28dp여야 해요.

2024-03-20 05:41 UTC, merged

2024-03-20 05:54 UTC, leeugun123 commented on app/src/main/res/layout/fragment_login_dialog.xml
> +            android:layout_marginTop="16dp"
제가 Dev 모드를 키지 않은 상태로 피그마를 봐서 marginTop까지 세세하게 체크하지 못한 것 같습니다. 다음 PR때 피그마 부분을 좀 더 유의해서 보겠습니다.

2024-03-22 04:11 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/LoginDialogFragment.kt
> +        * */
저도 TODO를 다는 방식으로 주석 처리 하겠습니당^^

2024-03-22 04:12 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/HomeActivity.kt
> +    }
저도 현재 최대한 정렬하려고 하는데 가끔씩 까먹네용ㅎㅎ;