Feature/26 문답생성UI 구현
ABloom-AOS/Merry_Android pull request #32
Opened 2024-03-21 01:54 UTC by yoonchanchoi

#### close #26

### ✏️ 개요

문답 생성 UI 구현

### 💻 작업 사항

문답 생성 UI 구현

### 📄 리뷰 노트

문답 생성 UI를 구현 하는 과정에서 
drawable 폴더를 생성했습니다. xdpi, xxdpi, xxxdpi가 추가 생성 되었고
삽입된 이미지 이름 현재 피그마 명칭을 따가 갔습니다. 이 부분은 논의해서 결정하고 싶습니다.
그리고 app.xml의 경우 Navigation args를 사용을 위해서 arguments부분이 추가 되었으며,
해당 데이터 전송 타입은 임시로 String을 썼다는 점 양해 부탁드립니당^^
CategoryFragment의 수정 코드는 해당 Navigation args 데이터 전송 확인을 위해서 임시적으로 추가 했습니다. 추후에 개발하는 과정에서 바꾸겠습니당^^
 

### 📱결과 화면(optional)

![1](https://github.com/abloom-AOS/MERY_Android/assets/74814647/dbf491ee-be1f-4393-a6d3-372f540c31ee)
![2](https://github.com/abloom-AOS/MERY_Android/assets/74814647/e7733d43-fbc5-413b-8136-4c5fcc7e18bf)

### 📚 ETC(optional)

Navigation args가 bundle보다 좋은 거 같습니다.ㅎㅎ

2024-03-21 06:59 UTC, leeugun123 requested changes

2024-03-21 06:59 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
>      }
수산확인이 잘 되었는지 확인하는 메소드 같은데 initData()라는 메소드명이 조금 어색하게 느껴집니다.
checkData() 라는 메소드명이 더 적절하지 않나 생각됩니다. 
제가 로직을 잘 파악하지 못해서 그런걸 수도 있으니 확인해주시면 감사하겠습니다!

2024-03-21 06:59 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
> +    }
initData()라는 메소드보다는 initTodayQuestion()라는 메소드명이 좀 더 코드를 파악하기 쉬울 것 같습니다!

2024-03-21 06:59 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
>      }
메소드명 잘 지어주셨네요

2024-03-21 06:59 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
> +    private fun goCategoryFragment(key: String, data: String) {
key를 매개변수로 받고 있지만 메소드 내에서 사용하고 있지 않는 것 같습니다.

2024-03-21 06:59 UTC, leeugun123 commented on app/src/main/res/layout/fragment_create_qna.xml
> +    <LinearLayout
constraintlayout을 사용하는 것이 정답 인줄 알았는데 이 부분은 LinearLayout을 사용하셨네요. 
혹시 LinearLayout을 사용하신 이유를 알 수 있을까요?

2024-03-21 06:59 UTC, leeugun123 commented on app/src/main/res/layout/fragment_create_qna.xml
> -            android:text="질문 선택하러"
string.xml에 추가하여 사용하는 것은 어떻게 생각하시나요?

2024-03-21 07:02 UTC, leeugun123 commented
부족한 실력이지만 코드 리뷰 남겼습니다. 
제 생각이 틀릴수도 있으니 "무조건 고쳐라"는 절대 아닙니다. 리뷰 확인해주시고 수정이 필요하다 생각되시면 수정해주시면 감사하겠습니다.
코드 리뷰를 해보니 당사자가 코드를 만들때 범하는 실수를 제3자의 리뷰를 통해 고칠 수 있어 정말 좋은 기회라고 생각됩니다.

2024-03-21 07:10 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
>      }
수정해서 올리겠습니다.!!!

2024-03-21 07:11 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
> +    }
수정하겠습니당!!

2024-03-21 07:11 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
> +    private fun goCategoryFragment(key: String, data: String) {
해당 부분 오늘 저녘까지해서 ViewModel과 Repository 작성 및 수정 해서 올리겠습니당^^

2024-03-21 07:13 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
>      }
checkData()가 조금 더 좋은 이름인거 같습니당^^

cc8e2baffc39eb82d6775c9fda5fc821f63d51cd

2024-03-21 07:14 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
> +    }
수정했습니당^^ 현재는 초기화는 되는 데이터 양이 많이 않아서 말씀하신 명칭이 더 잘 맞는 거 같습니다.

086ad2ab01f4506b59ba60929a567d221d2256ef

2024-03-21 07:14 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
>      }
감사합니당^^

2024-03-21 07:22 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_create_qna.xml
> +    <LinearLayout
해당 부분에 ScrollView를 사용해야 되는 상황이 발생했었습니다.
해당 Fragment의 화면 자체가 추천 질문의 의해서 아래로 사이즈가 늘어날 수 있고 그러므로 질문의 길이가 길어질 경우에 화면이 짤리는 상황 때문에 ScrollView를 사용하여 처리하려고 했으나 저희가 MaryAppbar를 커스텀으로 사용하는 도중이어서 ScrollView를 Maryappbar 상단에 위치 시킬 경우 에러 발생과 앱이 종료되는 오류가 생겨, 토마스에게 조언을 구하고 LinearLayout을 서서 MaryAppbar 하단에 ScrollView가 쌓이게 하여 해결했습니당
추가적으로 LinearLayout이 조금 더 가벼운 것으로 알고 있고 constrantlayout의 경우 제약을 추가 적으로 걸어 줘야되는 부분이 있어서 조금 더 좋다고 판단했습니당^^

2024-03-21 07:24 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_create_qna.xml
> -            android:text="질문 선택하러"
해당 코드는 삭제된 코드여서 추가 할 필요가 없다고 생각합니당^^

2024-03-21 07:29 UTC, leeugun123 commented on app/src/main/res/layout/fragment_create_qna.xml
> +    <LinearLayout
아 이해했습니다. 덕분에 잘 배워갑니다!

2024-03-21 07:29 UTC, leeugun123 commented on app/src/main/res/layout/fragment_create_qna.xml
> -            android:text="질문 선택하러"
아 삭제 됐네요. 다음 리뷰때는 좀 더 주의해서 보겠습니다.

2024-03-21 14:51 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
> +    }
해당 부분 임시로 더미 데이터 받는 부분이 생겨서 추가 수정했습니당
eb548ee97837607b1c05f9beee20995a2ca0b14b

2024-03-22 00:37 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
> +    private fun goCategoryFragment(key: String, data: String) {
해당 부분 key 삭제와 임시 로직 부분을 한번 짜서 간단한 더미 데이터와 함께서 해서 수정했습니다^^

eb548ee97837607b1c05f9beee20995a2ca0b14b

2024-03-22 01:30 UTC, ki960213 commented on app/src/main/res/layout/fragment_create_qna.xml
> +    <LinearLayout
앱바를 커스텀으로 사용하면 ScrollView에 위치시킬 경우 왜 에러 발생이 날까요? 안드로이드에서 기본적으로 제공하는 AppBar를 사용하면 에러 발생이 나지 않았나요?

2024-03-22 01:48 UTC, ki960213 requested changes
어제 xml 네이밍 규칙에 관한 블로그 주소를 알려드렸습니다.
https://week-year.tistory.com/135
하지만 이 블로그와 drawable 리소스의 네이밍이 다르네요. 혹시 다르게 하신 이유가 있을까요?

2024-03-22 01:48 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
>          }
저는 뷰를 초기화하는 로직과 viewModel의 데이터를 관찰하여 뷰를 변경하는 로직의 네이밍을 다르게 했습니다.

뷰를 초기화하는 경우: `setupXxx()`
viewModel의 데이터를 관찰하여 뷰를 변경하는 로직: `observeXxx()`

오른은 이렇게 네이밍을 달리하여 구분하는 것을 어떻게 생각하시나요?

2024-03-22 01:48 UTC, ki960213 commented on app/src/main/res/layout/fragment_create_qna.xml
> +                android:layout_height="match_parent">
여기서 IDE가 경고할거예요.
경고 메세지를 읽고 올바르게 고쳐주시면 감사하겠습니다 :)

2024-03-22 01:48 UTC, ki960213 commented on app/src/main/res/layout/fragment_create_qna.xml
> +                    android:clipToOutline="true"
저희의 minSdk는 26이지만 clipToOutline 속성은 그것보다 높은 버전에서만 쓸 수 있다고 IDE가 경고하고 있어요. 
저라면 background drawable을 만들어서 해결할 것 같아요.

2024-03-22 01:48 UTC, ki960213 commented on app/src/main/res/layout/fragment_create_qna.xml
> +                    app:layout_constraintTop_toTopOf="parent">
디자인 명세에 따르면 이 레이아웃이 앱바 바로 아래에 딱 붙지 않네요.
![image](https://github.com/abloom-AOS/MERY_Android/assets/123928686/b05ddeb3-55b0-4e04-8c0a-a961894c5906)

2024-03-22 01:48 UTC, ki960213 commented on app/src/main/res/layout/fragment_create_qna.xml
> +                        app:layout_constraintHorizontal_bias="0.5"
불필요한 속성은 지워주세용

2024-03-22 01:48 UTC, ki960213 commented on app/src/main/res/layout/fragment_create_qna.xml
> +                        android:layout_marginEnd="25dp"
이것도 불필요한 것 같아요 😢

2024-03-22 01:48 UTC, ki960213 commented on app/src/main/res/navigation/app.xml
> +                app:argType="long" />
여기서 question_id가 아니라 카테고리를 받아야 하지 않을까요? 왜냐면 특정 카테고리 이미지를 클릭하면 그 카테고리의 질문 목록을 보여줘야 하니까요. writeAnswer 화면에서는 question_id가 필요하지만 category 화면에서는 그렇지 않은 것 같아요 😢

2024-03-22 01:48 UTC, ki960213 commented on app/src/main/res/values/strings.xml
> +    <string name="createqna_recommend_question_title">오늘의 추천 질문</string>
문자열 리소스 네이밍을 깔끔하게 해주셨네요 👍

2024-03-22 04:28 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_create_qna.xml
> +    <LinearLayout
appbar와 Scrollview에 대해서 조금 더 찾아보고 말씀드리겠습니다. 추가적으로  혹시 수정 가능 하다면 수정하겠습니당 ㅎㅎ

2024-03-22 04:40 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
>          }
저도 말씀하신 방법이 더 좋다고 생각합니다.  수정하겠습니당

2024-03-22 04:47 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_create_qna.xml
> +                android:layout_height="match_parent">
맞네용 scrollView 하위에 있는 경우 해당 wrap_content를 써야되네용 수정하겠습니당

2024-03-22 04:54 UTC, ki960213 commented on app/src/main/res/layout/fragment_create_qna.xml
> +    <LinearLayout
ScrollView 안에 앱바를 배치할 경우 에러가 발생한 이유는 ScrollView 안에는 단 하나의 뷰만 배치할 수 있기 때문입니다. 그래서 보통 ScrollView의 가장 가까운 자식 뷰는 레이아웃 단 한 개만 넣습니다. 커스텀 앱바를 사용하는 중이라서 에러가 발생한 게 아닙니다.   
수정해달라는 의도는 아니였습니다 :)

2024-03-22 05:21 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_create_qna.xml
> +                    android:clipToOutline="true"
말씀하신대로 bg_shape_purple에서 자르도록 처리하면 필요 없을 것 같습니다.^^ 수정하겠습니다.
처음에 피그마에서 요소 가져온 후에 직접 구현해 놓고 지우는 걸 깜빡 했네용 ㅇㅅㅇ;;

2024-03-22 05:22 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_create_qna.xml
> +                        app:layout_constraintHorizontal_bias="0.5"
기본 값이 0.5되어 있어서 불필요한 속성이네요 수정하겠습니다.

2024-03-22 05:23 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_create_qna.xml
> +                        android:layout_marginEnd="25dp"
수정하겠습니다.

2024-03-22 05:29 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_create_qna.xml
> +    <LinearLayout
아하!! 그래서 상단에 배치하게 되면 appbar만 넣게 되어서 뜨지 않게 되었던거군요 한 가지 배워 갑니당!^^
scrollView, appbar간에 어떤 관계성이 있을 줄 알고 열심히 찾아보고 있었습니다. ㅇㅅㅇ;;
오늘 배운 것 블로그에 써서 남겨야겠습니다. 다음에 잊지 않기 위해서 ㅎㅎ

2024-03-22 05:32 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
>          }
해당 부분에 대해서 고민했던 부분인데 이렇게 수정하니깐 보기 좋네요^^

a3151cebd279cdaa601e170e9009713e27decd57

2024-03-22 05:34 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_create_qna.xml
> +                android:layout_height="match_parent">
수정했습니다

bc8b7ef3b462dfca919162e13ec224b79518c3e9

2024-03-22 05:35 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_create_qna.xml
> +                    android:clipToOutline="true"
수정했습니다

d1d18c407094fc50e85d3984777269e81eb9481d

2024-03-22 05:36 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_create_qna.xml
> +                        app:layout_constraintHorizontal_bias="0.5"
수정했습니다

04ec03109d4af0f60f486d84b36fb2c962c72194

2024-03-22 05:36 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_create_qna.xml
> +                        android:layout_marginEnd="25dp"
수정했습니다. 

e43abc5e6e25d9d929e7b7280bb8d765c8afbe40

2024-03-22 05:47 UTC, yoonchanchoi commented
토마스가 말씀하신 이미지 파일의 경우 아래 커밋 처럼 이미지 name을 수정했는데 

사용될 fragment의 이름과 해당 구분 요소로 해당 이미지의 종류+Img로 했습니다.
사이즈의 경우는 drawable에서 이름을 같게 해주어야 되는 부분이 있어서 일부러 뺐습니다. 
이렇게 의도 하신게 맞는지 모르겠어서 혹시 다른 의도가 있으시면 말씀해주세용^^

1de80ee1428a0ecf21fdf9144bd6c19b8f338eff

2024-03-22 05:48 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_create_qna.xml
> +                    app:layout_constraintTop_toTopOf="parent">
해당 부분 조금 확인 하고 말씀 드릴게용^^

2024-03-22 05:49 UTC, yoonchanchoi commented on app/src/main/res/navigation/app.xml
> +                app:argType="long" />
혹시 해당 부분에 그러면 category의 String 값이 들어가야 된다는 말씀이신가용?

2024-03-22 06:02 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_create_qna.xml
> +                    app:layout_constraintTop_toTopOf="parent">
앱바 사이즈 56dp 이기 때문에
해당 contrainlayout의 top 마진을 6으로 수정했습니당^^

81d21a3b337dcfa3780c1bbba14ea73bf3f5120b

2024-03-22 06:04 UTC, ki960213 commented on app/src/main/res/navigation/app.xml
> +                app:argType="long" />
저라면 타입 안정성을 얻기 위해 enum class로 만들 것 같아요. 그 예시는 WebViewUrl이라는 클래스입니다.

2024-03-22 06:16 UTC, ki960213 commented
> @ki960213 가 말씀하신 이미지 파일의 경우 아래 커밋 처럼 이미지 name을 수정했는데
> 
> 사용될 fragment의 이름과 해당 구분 요소로 해당 이미지의 종류+Img로 했습니다. 사이즈의 경우는 drawable에서 이름을 같게 해주어야 되는 부분이 있어서 일부러 뺐습니다. 이렇게 의도 하신게 맞는지 모르겠어서 혹시 다른 의도가 있으시면 말씀해주세용^^
> 
> [1de80ee](https://github.com/abloom-AOS/MERY_Android/commit/1de80ee1428a0ecf21fdf9144bd6c19b8f338eff)

createfrag(where)_children(description)_img(???)
img라는 접미사가 있는 게 컨벤션에 맞지 않다고 생각했습니다. 만약 img를 붙인다면 접두사로 붙이는 게 낫지 않을까요? 안드로이드 프로젝트 만들 때 기본 아이콘 이미지의 이름을 ic_launcher_background 로 명명하는 것 처럼요. 물론 이부분은 제가 어제 제시한 블로그 글에 나와있지 않은 부분이기 때문에 헷갈릴 수 있단 점 이해합니다. 😢 
그리고 where에 createfrag보단 createqna가 더 올바른 것 같아요.
![image](https://github.com/abloom-AOS/MERY_Android/assets/123928686/6a91aecc-81b4-401c-b34d-e4df8b6dba13)

2024-03-22 06:46 UTC, yoonchanchoi commented
@ki960213 제가 커밋을 쪼개서 올리다가 실수로 수정되지 않은 커밋이 올라간 거 같습니다.
그리고 수정된 부분이 다른 부분이랑 같이 올라간 거 같아요..ㅠㅠ

35d8027c7008fc553b0de3bcd2dada8a8f1599f1

현재는 원래 해당 부분처럼 createqna_communicationimg 
이런 식으로 수정되어 있는데 해당 부분에서 이미지만 빼서 올릴까요? 
![1](https://github.com/abloom-AOS/MERY_Android/assets/74814647/30e26208-7869-4335-bc7a-d9508f6f7107)

2024-03-22 06:46 UTC, yoonchanchoi commented on app/src/main/res/navigation/app.xml
> +                app:argType="long" />
참고 해서 수정하겠습니당!!

2024-03-22 07:40 UTC, yoonchanchoi commented
이미지 명칭 수정 했습니다.

f9d8d4088b80640dce0a6db349225cb144a1351a

2024-03-22 07:40 UTC, yoonchanchoi commented on app/src/main/res/navigation/app.xml
> +                app:argType="long" />
수정 했습니다

73f9cba20a4325df55da94133ccddbc529f7f8d9

2024-03-22 08:17 UTC, ki960213 approved these changes
문답 생성 UI 구현하느라 고생하셨습니다 👍

2024-03-22 12:30 UTC, leeugun123 requested changes

2024-03-22 12:30 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/createqnaretest/CreateQnaViewModel.kt
> +        }
코루틴을 사용하여 비동기작업 잘 구현해주셨네요!!

2024-03-22 12:30 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/createqnaretest/IdRepository.kt
> +        val userInfo = CoroutineScope(Dispatchers.IO).async {
이미 Dispatchers.IO 쓰레드 풀이기 때문에 별도의 코루틴  Scope를 정의 해주시지 않아도 될 것 같습니다.

val userInfo = requestUserInfo()로 바꿔보시고 테스트 해주세요!

2024-03-22 12:30 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/createqnaretest/IdRepository.kt
> +        }
여기도 userInfo = requestUserInfo()로 수정해주세요!

2024-03-22 12:30 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/createqnaretest/IdRepository.kt
> +    }
private suspend fun requestUserInfo() = UserInfo(1, arrayListOf("질문1", "질문2" , "질문3" , "질문4", "질문5"))
로 수정하시면 가독성면에서 읽기 더 좋을 것 같습니다.

2024-03-22 12:30 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/createqnaretest/UserInfo.kt
> +    val questions : ArrayList<String> = arrayListOf("1","2","3")
코틀린은 변수 선언 시 타입추론을 자동적으로 수행하기 때문에 
val questions = arrayListOf("1","2","3")으로 선언하셔도 될 것 같습니다!

2024-03-22 12:33 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
>          }
저도 viewModel을 사용해서 데이터를 가져오는 경우, 토마스 말씀처럼 네이밍을 사용하여 메소드를 짓는 것이 좋을 것 같습니다.

2024-03-22 13:20 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/createqnaretest/UserInfo.kt
> +    val questions : ArrayList<String> = arrayListOf("1","2","3")
해당 부분 은 data class 클래스의 매개변수 부분이기 때문에 일반적으로 type선언을 무조건 해주어야 되는 걸로 알고 있습니다 ^^

2024-03-22 13:21 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/createqnaretest/IdRepository.kt
> +    }
말씀대로 해당 코드 대로 수정하면 조금 더 좋은 가독성을 볼 수 있을거 같습니다. 수정하겠습니다.

2024-03-22 13:25 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/createqnaretest/IdRepository.kt
> +        }
수정하겠습니당^^

2024-03-22 13:25 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/createqnaretest/IdRepository.kt
> +        val userInfo = CoroutineScope(Dispatchers.IO).async {
수정 하겠습니다.
다만 한 가지 궁금한 점이 있습니다. 
해당 Dispatchers가 IO 쓰레드 풀인 이유가 뷰모델에서 IO로 스레드 풀을 설정했기 때문인건가용?

2024-03-22 13:31 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/createqnaretest/UserInfo.kt
> +    val questions : ArrayList<String> = arrayListOf("1","2","3")
검색해보니 데이터 클래스는 모든 변수나 프로퍼티에 대한 타입 정보를 컴파일 시점에 알고 있어야 하니 타입 선언이 필수적이라고 하네요. 새롭게 배웠네요!

2024-03-22 13:32 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/createqnaretest/UserInfo.kt
> +    val questions : ArrayList<String> = arrayListOf("1","2","3")
수정 대신 IDE 단축키를 써서 전체 코드 정렬 했습니당^^

3d1e849fae385c5f8877091abdebc6061333a009

2024-03-22 13:32 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/createqnaretest/IdRepository.kt
> +    }
수정했습니당^^

1c346fa49fd1efdab6a47f69344a5bf615ae5e5f

2024-03-22 13:32 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/createqnaretest/IdRepository.kt
> +        }
수정했습니당^^

c0e3e605bf70cef9b1cfa2d862cd08f21cf90cf0

2024-03-22 13:32 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/createqnaretest/IdRepository.kt
> +        val userInfo = CoroutineScope(Dispatchers.IO).async {
수정했습니다

c0e3e605bf70cef9b1cfa2d862cd08f21cf90cf0

2024-03-22 13:37 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/createqnaretest/IdRepository.kt
> +        val userInfo = CoroutineScope(Dispatchers.IO).async {
> 수정 하겠습니다. 다만 한 가지 궁금한 점이 있습니다. 해당 Dispatchers가 IO 쓰레드 풀인 이유가 뷰모델에서 IO로 스레드 풀을 설정했기 때문인건가용?

네 맞습니다. 뷰모델에서 이미 IO 스레드 풀을 설정했기 때문에 비동기 작업을 위한 별도의 코루틴 스코프를 생성하지 않아도 됩니다.
만약 생성 할 경우 오버헤드도 생길 수 있고 데이터 흐름도 파악하기 어렵습니다.

제가 저번에 디스코드에서 말씀드린  Room Null로 인해 앱이 꺼진 사건도 무지성으로 Repo에서 또 다시 코루틴을 구현하다가 일어나는 일이기 때문에 웬만하면 별도의 스코프를 정의하지 않는 것이 좋다고 생각됩니다.

2024-03-22 13:38 UTC, leeugun123 approved these changes

2024-03-22 13:45 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/createqnaretest/IdRepository.kt
> +        val userInfo = CoroutineScope(Dispatchers.IO).async {
아하!! 저도 한 가지 더 배워 갑니당!!!

2024-03-22 14:11 UTC, merged