Feature/31 회원가입 step01 UI 개발
ABloom-AOS/Merry_Android pull request #33
Opened 2024-03-21 09:39 UTC by leeugun123

#### close #31

### ✏️ 개요

회원가입 step01 UI 개발

### 💻 작업 사항

회원가입 step01 UI 개발

### 📄 리뷰 노트

예비신랑 , 예비 신부 버튼을 중점적으로 리뷰 해주시면 감사하겠습니다.

### 📱결과 화면(optional)

리뷰어의 이해를 위해 스크린샷을 추가해주세요.

### 📚 ETC(optional)

예비 신랑 , 예비 신부 버튼에서 피그마와 달리 가운데 정렬은 하지 못했습니다.
(가운데 정렬시 글자 수가 달라 예비 신랑 신부 간격이 동일하지 않는 문제 발생)

2024-03-21 15:27 UTC, yoonchanchoi commented
깔끔 하네요^^ 그리고 xml도 잘 나오는 거 같아서 다행이네요!!!
저 개인적으로 궁금한게 있습니다. bindinginit() 이라는 부분 저는 보통 initListener()라고 많이 쓰는데 조금 가독성이 조금 떨어질까요? 그렇다면 저도 저렇게 수정해서 쓸까 합니당^^

2024-03-22 01:21 UTC, ki960213 requested changes
구현 잘 해주셨네요 👍 
몇 가지 코멘트 남겼습니다 :)

2024-03-22 01:21 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +
푸시하기 전에 코드 정렬 해주시면 감사하겠습니다 :)

2024-03-22 01:21 UTC, ki960213 commented on app/src/main/res/drawable/progress_horizontal_custom.xml
> +</layer-list>
커스텀 진행 Drawable 👍

2024-03-22 01:21 UTC, ki960213 commented on app/src/main/res/drawable/signup_selected.xml
> +</shape>
색상을 보니 선택되지 않은 버튼의 배경인 것 같아요.

2024-03-22 01:22 UTC, ki960213 commented
> 깔끔 하네요^^ 그리고 xml도 잘 나오는 거 같아서 다행이네요!!! 저 개인적으로 궁금한게 있습니다. bindinginit() 이라는 부분 저는 보통 initListener()라고 많이 쓰는데 조금 가독성이 조금 떨어질까요? 그렇다면 저도 저렇게 수정해서 쓸까 합니당^^

저도 동의합니다. binding 객체를 초기화한다는 말보다 조금 더 함수가 하는 일을 구체적으로 작성한다면 더 좋은 이름이 도

2024-03-22 12:37 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +
commit마다 정렬하는 습관이 아직 덜 된 것 같습니다. 이후 PR때 최대한 실수를 줄여보겠습니다.

2024-03-22 12:54 UTC, leeugun123 commented on app/src/main/res/drawable/signup_gender_selected.xml
> +    <solid android:color="#F6ECFA" />
Color 폴더에 "#F6ECFA"이 없어서 직접 명시했습니다.

2024-03-22 12:56 UTC, leeugun123 commented
> 깔끔 하네요^^ 그리고 xml도 잘 나오는 거 같아서 다행이네요!!! 저 개인적으로 궁금한게 있습니다. bindinginit() 이라는 부분 저는 보통 initListener()라고 많이 쓰는데 조금 가독성이 조금 떨어질까요? 그렇다면 저도 저렇게 수정해서 쓸까 합니당^^

저도 initListener()라는 메소드명이 더 적절한 것 같습니다. 수정했습니다!
14a4c16d74dea18457033021d9f9bd7b87902129

2024-03-22 12:57 UTC, leeugun123 commented on app/src/main/res/drawable/signup_selected.xml
> +</shape>
selected와 unselected background를 각각 만들었습니다.
e2d52ceff6f638ce572cfb84425ca8ddf4154ae7

2024-03-22 13:04 UTC, ki960213 commented on app/src/main/res/drawable/signup_gender_selected.xml
> +    <solid android:color="#F6ECFA" />
저 색상이 이전 디자인 시스템의 BI/Primary/Purple-01 이군요 😢 
![image](https://github.com/abloom-AOS/MERY_Android/assets/123928686/c52f42ea-622a-449f-a4ac-ea71e833672b)

2024-03-22 13:08 UTC, ki960213 approved these changes
고생하셨습니다 👏

2024-03-22 13:35 UTC, yoonchanchoi commented
고생하셨습니당!!!

2024-03-22 13:38 UTC, yoonchanchoi commented on app/src/main/res/drawable/progress_horizontal_custom.xml
> +</layer-list>
프로그래스바 커스텀 ㅎㅎ
👍

2024-03-22 13:38 UTC, yoonchanchoi approved these changes

2024-03-22 13:46 UTC, merged