[Feat/35] Signup Step02 결혼 날짜 선택 UI 구현
ABloom-AOS/Merry_Android pull request #37
Opened 2024-03-24 14:14 UTC by leeugun123

#### close #35

### ✏️ 개요

Signup Step02 결혼 날짜 선택 UI 구현

### 💻 작업 사항

Signup Step02 결혼 날짜 선택 UI 구현

### 📄 리뷰 노트

DatePicker 디자인은 임시로 구현하였습니다.

### 📱결과 화면(optional)

<img width="432" alt="Screenshot 2024-03-24 at 11 08 43 PM" src="https://github.com/abloom-AOS/MERY_Android/assets/50404123/2ed736ef-2a68-4444-9ed7-c9de9f5be5c6">

2024-03-24 14:16 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/createqnaretest/CreateQnaViewModel.kt
해당 부분에 오타가 있어 수정하였습니다!

2024-03-24 14:16 UTC, leeugun123 commented on app/src/main/res/layout/fragment_marry_date.xml
> +        <DatePicker
임시적으로 DatePicker를 사용하여 UI를 구성하였습니다.

2024-03-24 14:28 UTC, ki960213 requested changes
빠르고 적은 범위의 코드 리뷰를 할 수 있어서 좋았어요 👍 
만약 지금 방식대로 가입하기 화면의 4단계 화면을 모두 만들었다면 바꿔야 할 게 더 많았을 것 같아요.

2024-03-24 14:28 UTC, ki960213 commented on app/src/main/res/layout/fragment_marry_date.xml
> +            app:layout_constraintStart_toStartOf="parent"
가입할 때 각 화면마다 프래그먼트를 만든다면 IOS 시연 영상대로 ProgressBar를 늘리고 줄이는 애니메이션을 구현할 수 있을까요? 완전히 다른 레이아웃이라 힘들 것 같아요. 제가 만약 가입하기 화면을 만든다면 AppBar와 ProgressBar, FragmentContainerView 세 뷰만 존재하고 가입 단계에 따라 FragmentContainerView 안의 프래그먼트를 변경하는 식으로 이동할 것 같아요. 이 작업을 위해 새로운 내비게이션을 만들면 IOS 시연 영상대로 화면 전환 시 fade in, fade out을 구현하기도 쉽고요.
그리고 각 단계마다 AppBar의 navigation 버튼과 액션 버튼이 달라지는데, 이 상황을 염두하고 MeryAppBar의 바인딩어댑터를 구현한 것입니다 😄

2024-03-24 21:39 UTC, leeugun123 commented on app/src/main/res/layout/fragment_marry_date.xml
> +            app:layout_constraintStart_toStartOf="parent"
저도 이 부분에서 많은 고민을 했었는데 명확하게 해결책을 제시해주셔서 감사합니다.
FragmentContainerView를 이용해서 구현해보겠습니다.

2024-03-25 04:44 UTC, leeugun123 commented on app/src/main/res/layout/fragment_marry_date.xml
> +            app:layout_constraintStart_toStartOf="parent"
@ki960213 토마스 질문이 있습니다! 내비게이션을 만들때 새로 따로 파일을 만들어야 하나요? 아님 이미 만들어진 app안에 프래그먼트를 정의해야 하나요?

2024-03-25 04:45 UTC, ki960213 commented on app/src/main/res/layout/fragment_marry_date.xml
> +            app:layout_constraintStart_toStartOf="parent"
따로 만들어야 합니다!

2024-03-25 09:04 UTC, leeugun123 commented on app/src/main/res/layout/fragment_marry_date.xml
> +            app:layout_constraintStart_toStartOf="parent"
4a55be1572b7e783cf060d83ad98aeade2c66577 수정하였습니다.

2024-03-25 10:42 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/createqnaretest/CreateQnaViewModel.kt
감사합니당 ㅎㅎ

2024-03-25 12:00 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_marry_date.xml
> +            app:layout_constraintStart_toStartOf="parent"
FragmentContainerView를 통해서 controller하시는 거 보고 놀랬습니당!!

2024-03-25 12:36 UTC, ki960213 requested changes
몇 가지 코멘트 남겼습니다. 확인부탁드려요 😊

2024-03-25 12:36 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/BrideGroomSelectionFragment.kt
> +    }
코드 정렬 부탁드립니다 😓

2024-03-25 12:36 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    }
[코틀린 코딩 컨벤션](https://medium.com/mj-studio/%EC%BD%94%ED%8B%80%EB%A6%B0-%EC%9D%B4%EB%A0%87%EA%B2%8C-%EC%9E%91%EC%84%B1%ED%95%98%EC%8B%9C%EB%A9%B4-%EB%90%A9%EB%8B%88%EB%8B%A4-94871a1fa646)의 클래스 구조에 따르면 companion object의 위치는 여기가 아닌 것 같아요...!

2024-03-25 12:36 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    private val signUpStepNavController: NavController by lazy { childNavController.navController }
두 내비게이션의 차이를 잘 알고 사용하신 것 같군요 👍 
한 가지 아쉬운 점은 `NavHostFragment` 객체의 이름이 `childNavController`라는 것입니다.
`NavHostFragment`와 `NavController`의 차이를 생각한다면 `childNavController` 대신 다른 이름을 사용하는 게 좋을 것 같아요.

2024-03-25 12:36 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    private var currentStep = STEP_BRIDE_GROOM_SELECTION
현재 어떤 페이지를 보여주고 있는지에 대한 상태를 유지하고 있네요. 이 상태를 Fragment의 멤버 변수로 유지한다면 구성 변경 시 어떤 문제가 발생할까요?

2024-03-25 12:36 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    }
`signUpStepNavController.currentDestination`로 현재 보여지고 있는 대상을 알 수 있다면 `currentStep`으로 어떤 단계인지 유지할 필요가 없을 것 같아요.

2024-03-25 12:36 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
>      }
`observeSignUpStepChanges()`에서 이미 각 대상에 대해 분기 처리 하고 있는데, `updateUIForStep()` 함수에서 또 다시 분기 처리를 할 필요가 있을까요?

2024-03-25 12:36 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    }
잊지 않고 액션 버튼 비활성화 해주신 점 좋았어요 👍 
```kotlin
private fun setupForBrideGroomSelection() {
    binding.appbarSignUp.apply {
        title = getString(R.string.signup_title)
        navigationText = getString(R.string.all_cancel)
        actionText = ""
        isActionEnabled = false
    }
}
```
참고로, navigationText를 설정하면 navigationIcon은 자동으로 사라지게 구현했습니다 😊 
또한, 함수 대신 프로퍼티를 변경하는 게 가독성이 더 좋다고 생각합니다. IDE에서도 그걸 권장하고 있어요. 제가 MeryAppBar의 `setXxx()`같은 함수를 만든 이유는 바인딩 어댑터를 구현하기 위함입니다.

2024-03-25 12:36 UTC, ki960213 commented on app/src/main/res/layout/fragment_bride_groom_selection.xml
> +     -->
이 코드는 제가 틀 만들 때 임시로 만든 것이니 지워도 될 것 같아요. 😄

2024-03-25 12:36 UTC, ki960213 commented on app/src/main/res/layout/fragment_bride_groom_selection.xml
> +        android:background="@drawable/bg_page"
이 프래그먼트의 배경은 없어도 될 것 같아요. signup프래그먼트 안에 들어가는 프래그먼트니까요 😊

2024-03-25 12:36 UTC, ki960213 commented on app/src/main/res/navigation/app.xml
> +
실수로 지우지 않은 것 같아요...!

2024-03-25 12:36 UTC, ki960213 commented on app/src/main/res/navigation/signup_nav_graph.xml
> +
잘 구현해주셨군요!
작업 간에 애니메이션도 구현해주시면 좋을 것 같지만 어렵다면 제가 하겠습니다 😊

2024-03-25 12:36 UTC, ki960213 commented on app/src/main/res/values/strings.xml
> +    <string name="all_next">다음</string>
다른 문자열 아이디 패턴에 맞게 센스있게 만들어주셨군요 👍

2024-03-25 14:03 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/BrideGroomSelectionFragment.kt
> +    }
f461d62fa9fb8b730898d5f65fe8fe81eb3b5507 
실수를 계속 줄여나가겠습니다.

2024-03-25 14:04 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    }
d17870e6c20a39ff3994dabeea12104d2114b4c7 
수정하였습니다. 덕분에 많이 배워갑니다!

2024-03-25 14:05 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    private val signUpStepNavController: NavController by lazy { childNavController.navController }
67c684a119bb6ed67f8e3371f6d42a1e6ad262ba 막상 구현에 집중하느라 변수명에 신경 쓰지 못했네요. 적절한 변수 이름으로 수정하였습니다.

2024-03-25 14:06 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    }
62b9df08fc5915f366809fa5fd30e5947696811b
signUpStepNavController.currentDestination으로 현재 프래그먼트를 알 수 있었군요.. 많이 배우게 됩니다.

2024-03-25 14:07 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
>      }
59428460b0f8ee70adf7174b4b6fd189dced7cfa
불필요한 분기처리를 구현한 것 같습니다. 수정했습니다!

2024-03-25 14:08 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    }
c7b795597f7a1289c29bf2ce67a86481cd21f7ac
함수로 사용하지 않고 이렇게 프로퍼티를 변경하는게 가독성이 훨 좋네요! 수정하였습니다.

2024-03-25 14:09 UTC, leeugun123 commented on app/src/main/res/layout/fragment_bride_groom_selection.xml
> +     -->
bd118b6270b8e82d5c17cedddbc6229007384f97
수정하였습니다.

2024-03-25 14:09 UTC, leeugun123 commented on app/src/main/res/layout/fragment_bride_groom_selection.xml
> +        android:background="@drawable/bg_page"
e24a7fa881c4c94570322f7855c3f8382449b963
수정하였습니다.

2024-03-25 14:10 UTC, leeugun123 commented on app/src/main/res/navigation/app.xml
> +
9d5343197e9afd8aec798ff9b40360b0051f17e6 앗.. 지우는 걸 깜빡했네요! 수정했습니다.

2024-03-25 14:11 UTC, leeugun123 commented on app/src/main/res/navigation/signup_nav_graph.xml
> +
한번 스스로 구현해보고 어려운 부분이 있으면 토마스에게 도움을 구해보겠습니다.

2024-03-25 14:17 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    private var currentStep = STEP_BRIDE_GROOM_SELECTION
62b9df08fc5915f366809fa5fd30e5947696811b

제가 생각하기로는 유지보수하기도 여려울 뿐더러 메소드를 구현 할때 currentStep을 임의로 변경 할 가능성이 있다고 생각됩니다.

2024-03-26 07:56 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    private var currentStep = STEP_BRIDE_GROOM_SELECTION
구성 변경이란 런타임에 화면 회전, 시스템 크기나 글자 크기 변경 등 리소스를 선택하는 기준이 변경되는 것입니다. 구성 변경이 일어나면 액티비티의 인스턴스가 삭제되었다가 다시 생성됩니다. 따라서 currentStep의 값은 항상 처음 할당된 `STEP_BRIDE_GROOM_SELECTION`로 되돌아갈 것입니다.

2024-03-26 07:57 UTC, ki960213 approved these changes
리뷰 반영하느라 고생하셨습니다 👍

2024-03-26 08:43 UTC, yoonchanchoi approved these changes

2024-03-26 08:43 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    }
확실히 저렇게 쓰는게 가독성 좋네요 무엇보다 조금 직관적이네용^^

2024-03-26 08:43 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    }
저도 수정하려 갑니당^^

2024-03-26 08:43 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    private var currentStep = STEP_BRIDE_GROOM_SELECTION
저도 해당 공식문서 보고 수정해야될 부분인지 확인 해봐야겠네용

2024-03-26 08:43 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    }
확실히 직관적이라고 생각합니당

2024-03-26 11:19 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    private var currentStep = STEP_BRIDE_GROOM_SELECTION
아 제가 구성변경을 잘못 이해하고 있었던 것 같습니다. 토마스가 말씀하신것처럼 화면 회전이나 여러가지 구성 변경이 일어날시
액티비티의 인스턴스가 재생성되는 경우를 간과했네요ㅠㅠ 앞으로 개발할때 이부분에 좀 더 유의해서 만들겠습니다.
가르쳐주셔서 감사합니다!

2024-03-26 11:24 UTC, merged