[Feature/#36] 질문 카테고리 UI 구현
ABloom-AOS/Merry_Android pull request #40
Opened 2024-03-26 03:38 UTC by yoonchanchoi

#### close #36 

### ✏️ 개요

질문 카테고리 UI 구현

### 💻 작업 사항

질문 카테고리 UI 구현

### 📄 리뷰 노트

해당 로그인 상태를 체크하는 부분이 observe로 되어 있습니다.
현재는 로그인 상태일 때로 데이터를 넣어 놓았습니다.
그리고 비로그인시 해당 로그인 버튼을 누르면 다이얼로그가 뜨도록 되어있는데
jay와 이야기후에 추후에 해당 부분은 조금 로직이 변경될 수도 있을 거 같습니다.

### 📱결과 화면(optional)

![1](https://github.com/abloom-AOS/MERY_Android/assets/74814647/163ca6ae-ca0c-45d9-b20f-3e1dc7a5be77)
![2](https://github.com/abloom-AOS/MERY_Android/assets/74814647/152111c5-543f-4f76-9908-6d13965d0f89)
![3](https://github.com/abloom-AOS/MERY_Android/assets/74814647/f1309f53-e9c9-431a-95c4-1eebd9cc8441)

### 📚 ETC(optional)

혹시 해당 selectTabItem() 해당 함수 부분에 더 좋은 로직이 있거나 문제가 있으면 말해주시면 감사하겠습니다.
해당 부분 @ki960213의 도움을 받아 처음에 처리했고 현재 개인적인 판단에 의해 로직을 조금 수정했습니다.
하지만 조금 불확실해서 도움을 받고자 합니다.

2024-03-26 12:24 UTC, ki960213 requested changes
몇 가지 생각해볼만한 코멘트 남겼습니다. 확인 부탁드려요 😊

2024-03-26 12:24 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/common/util/IntExt.kt
> +}
이 코드가 선언된 파일명은 `IntExt.kt`입니다. Int 타입의 확장 함수를 선언한 코드가 있다는 뜻입니다.
`IntExt.kt` 파일 대신 다른 적절한 이름을 가진 파일에 옮기면 좋을 것 같습니다. 그리고 `invoke`는 제거해도 될 것 같습니다. 😊

2024-03-26 12:24 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryAdapter.kt
> +) : RecyclerView.Adapter<CategoryViewHolder>() {
`ListAdapter`를 사용한다면 변경된 항목에 맞게 필요한 연산만 합니다. 그리고 비동기적으로 리사이클러 뷰가 보여줄 항목들을 갱신합니다. `notifyDataSetChanged()`는 모든 데이터를 갱신하기 때문에 비효율적일 수 있습니다. 물론 저희 앱에서는 질문 목록 중 일부만 변경하는 경우가 없기 때문에 불필요할 수 있지만, 저는 `ListAdapter`를 알고난 뒤로 `RecyclerView.Adapter`를 사용한 적이 없습니다. 이 부분은 선택적으로 반영해주셔도 좋을 것 같아요 👍

2024-03-26 12:24 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryAdapter.kt
> +        }
수신 객체 지정 함수를 사용해서 얻는 이점이 무엇일까요? 그리고 이 코드에서 `let`을 사용해서 그 이점을 얻었을까요?
```kotlin
if (movies != null) this.questionList = movies
```
이렇게 작성하는 게 더 가독성이 좋은 것 같아요. 그리고 위 코드에서 `movies`는 non-nullable이기 때문에 null 안전 코드를 사용할 필요도 없는 것 같아요 😢

2024-03-26 12:24 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +        private val PAST_TABITEM_POSION by lazy { 11 }
과연 Int 타입 객체를 사용될 때 생성하도록 하는 게 메모리 절약에 도움이 될까요? `by lazy`를 사용하면 lazy 객체를 생성하기 때문에 잘 모르겠네요. 😕

2024-03-26 12:24 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +    companion object {
[코틀린 코딩 컨벤션](https://medium.com/mj-studio/%EC%BD%94%ED%8B%80%EB%A6%B0-%EC%9D%B4%EB%A0%87%EA%B2%8C-%EC%9E%91%EC%84%B1%ED%95%98%EC%8B%9C%EB%A9%B4-%EB%90%A9%EB%8B%88%EB%8B%A4-94871a1fa646)에 맞게 `companion object`의 위치를 변경해주시면 좋을 것 같아요.

2024-03-26 12:24 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +    }
이전에 얘기했던대로 뷰모델을 관찰하는 코드는 `observeXxx` 네이밍으로 변경하면 좋을 것 같아요. 이 부분에 대해 컨벤션 문서를 만드는 것도 좋을 것 같네요

2024-03-26 12:24 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +    private fun initListener() {
뷰를 초기화하는 함수의 이름이 `setupXxx`, `initXxx`로 나뉘어 있네요. 😢 하나로 통일하는 게 좋아보여요

2024-03-26 12:24 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +    }
```kotlin
private fun observeCategory() {
    viewModel.questions.observe(viewLifecycleOwner, categoryAdapter::setData)
}
```
이렇게 함수 참조로 코드를 줄일 수도 있어요 😄

2024-03-26 12:24 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +    }
문자열 대신 enum class인 `CreateQnaCategory` 타입으로 분기처리 한다면 IDE의 도움을 받아 더 쉽게 구현할 수 있고, 문자열을 오타내 버그를 발생할 확률도 낮아질 것 같아요.
![image](https://github.com/abloom-AOS/MERY_Android/assets/123928686/d5678337-e523-4ce3-a87f-93ef7804405c)

2024-03-26 12:24 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryRecyclerListener.kt
> +}
이 인터페이스를 만들 필요가 있을까요? 리사이클러 뷰 어댑터에 콜백 함수만 넣는다면 `CategoryRecyclerListener`같은 인터페이스를 만들 필요가 없어보여요.

2024-03-26 12:24 UTC, ki960213 commented on app/src/main/res/drawable/category_children.xml
> +</selector>
selector 사용 👍

2024-03-26 12:24 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +        }
`setScrollPosition`을 `Dispatchers.Main` 스레드에서 실행되도록 코루틴 컨텍스트를 변경하신 이유를 여쭤봐도 되나요?
`selectTab`은 코루틴으로 실행하지 않아도 될 것 같아요. 👍

2024-03-26 12:24 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryAdapter.kt
> +    }
[어댑터 패턴](https://refactoring.guru/ko/design-patterns/adapter)에서 어댑터의 역할은 클라이언트가 서비스를 사용하기 위해 서비스를 클라이언트 인터페이스로 래핑해서 클라이언트와 협업할 수 있도록 하는 것입니다. 이 상황에 대입해보면 클라이언트는 `RecyclerView`, 서비스는 `Question`, 클라이언트 인터페이스는 뷰 홀더입니다. 따라서 바인딩 객체를 생성하는 책임은 어댑터 대신 뷰 홀더에 위임하는 것이 적절한 책임 할당으로 보여집니다. 다시 말해, 어댑터는 단지 `parent`를 넘겨주고, `parent` 하위에 붙여질 뷰는 뷰 홀더가 생성해서 가지고 있는 것이 적절한 책임 할당이라고 생각합니다.

2024-03-26 12:24 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryViewHolder.kt
> +        }
클릭 리스너는 바인딩 될 때마다 변경될 필요는 없어보여요. 클릭 되었을 때 어떤 질문이 클릭되었는지만 달라질 뿐 같은 로직을 실행하니까요.

2024-03-26 12:24 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaCategory.kt
> +    PAST("past")
이 클래스는 `CategoryFragment`에 진입하기 위한 인자로서 사용됩니다. 따라서 createqna 패키지 대신 category 패키지에 놓는 것이 더 응집도가 높다고 생각합니다.

2024-03-26 12:38 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/common/util/IntExt.kt
> +}
말씀하신대로 파일명에 따라서 분리하는 편이 좋은거 같습니다. 
새벽에 코드를 짜다보니 IntExt를 생각 못했네요 ㅠㅠ
다른 파일에 넣도록 하겠습니다.^^ 
그렇다면 해당 category패키지 안쪽에  CategoryUtil이라는 이름으로 만들까 합니다. 괜찮을까용?

2024-03-26 12:40 UTC, leeugun123 requested changes

2024-03-26 12:40 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/categorytest/CategoryRepository.kt
> +    }
fun isLoginCheck() = true로 바꾸셔도 좋을 것 같습니다.

2024-03-26 12:40 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/categorytest/CategoryRepository.kt
> +    private fun requestQuestions(): List<Question> = FakeQuestions().questions
참고로 private fun requestQuestions() = FakeQuestions().questions 으로 작성이 가능합니다.
하지만 어떤 자료형인지 명확하게 파악하고 싶으시면 지금 이대로 작성하셔도 무방합니다.

2024-03-26 12:40 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/categorytest/CategoryViewModel.kt
> +        val check = repository.isLoginCheck()
loginCheck라는 변수명이 코드를 파악하는데 더 쉬울 것 같습니다.

2024-03-26 12:40 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/categorytest/FakeQuestions.kt
> +)
만드시느라 고생 많으셨어요!

2024-03-26 12:40 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryAdapter.kt
> +    }
이부분도 override fun getItemCount() = questionList.size으로 수정하시면 가독성 면에서 더 좋을 것 같습니다.

2024-03-26 12:40 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +            when (it) {
it이 아닌 구체적인 변수명을 짓는 것이 코드 파악이 더 쉬울 것 같습니다.

2024-03-26 12:40 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +    private val viewModel: CategoryViewModel by viewModels()
categoryViewModel로 변수명을 짓는 것이 가독성면에서 더 좋을 것 같습니다.

2024-03-26 12:40 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +            }
카테고리 분류 깔끔하네요!!

2024-03-26 12:40 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
>          binding.appbarCategory.setOnNavigationClick {
이 부분도 initListener 메소드에 포함시키는 것은 어떻게 생각하시나요?

2024-03-26 12:40 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +        lifecycleScope.launch {
해당 비동기부분을 따로 메소드로 처리하시는게 코드가 더 깔끔할 것 같습니다.

2024-03-26 12:40 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +        viewModel.requestQuestion(category)
이 부분도 재사용 될 수 있으니 따로 메소드 처리하시는게 좋을 것 같습니다.

2024-03-26 12:40 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +        private const val PAST_TABITEM_POSION = 11
private로 작성하신 이유를 알 수 있을까요?

2024-03-26 12:43 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +            when (it) {
지금 전체적으로 observe 패턴에서 it이 사용되고 있는데 
이를 좀 더 명확한 변수명으로 수정하시는 것이 코드 로직을 파악하는데 더 쉬울 것 같습니다.

2024-03-26 12:46 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/categorytest/CategoryViewModel.kt
> +        val check = repository.isLoginCheck()
함수명은 일반적으로 동사를 먼저 쓰는 게 일반적인 네이밍입니다. 😓

2024-03-26 12:50 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/categorytest/CategoryRepository.kt
> +    private fun requestQuestions(): List<Question> = FakeQuestions().questions
개인적으로 코틀린에서 함수나 멤버 변수에 반환 타입을 선언하는 기준이 있습니다.
함수나 멤버 변수 바로 오른쪽에 클래스 이름이 있으면 반환 타입을 선언하지 않습니다. 매우 쉽게 타입을 알 수 있기 때문입니다. 하지만 위의 경우 바로 오른쪽에 반환 타입과 다른 `FakeQuestions` 클래스가 있으니 저라면 반환 타입을 선언합니다.
이펙티브 코틀린에서도 반환 타입을 추론 타입으로 선언하지 않는 것을 권장합니다. https://augustin26.tistory.com/m/27

2024-03-26 13:54 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryAdapter.kt
> +) : RecyclerView.Adapter<CategoryViewHolder>() {
해당 부분은 ListAdapter를 조금 찾아보고 적용할 수 있으면 한번 해보겠습니당!!

2024-03-26 13:57 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/common/util/IntExt.kt
> +}
category패키지 안쪽에 넣었습니다.!!
25e571ca7c6d03bb6d2dc37473c0e5dcc6bcb4d1

2024-03-26 14:14 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryAdapter.kt
> +        }
말씀하신 해당 let의 경우는 데이터의 null값이 들어왔는지 판별하고 null이 아닐 경우에 데이터를 넣어 주기 위해서 사용합니다. 그런 부분에 있어서 사용했지만 저희 movies데이터의 경우 토마스가 말씀한데로 non-nullable이기 때문에 사용할 필요가 없을 것 같습니다. 추가적으로 가독성면에서도 이점이라고 생각했는데 해당 null판별할 필요가 없어진 점에서 오히려 토마스가 제시해준 방법이 더 가독성이 좋은거 같습니당^^
참고로 중첩쓰면 가독성이 엄청 떨어진다고 하네용 ㅎㅎ

495adca3f3222fa7a91e7546074b0cfc51e10eae

2024-03-26 14:25 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +        private val PAST_TABITEM_POSION by lazy { 11 }
토마스가 말씀하신대로 메모리 절약보다는 하당 int의 가독성을 위해서 사용하는 것이 맞다고 생각합니다. ^^
추가적으로 private을 사용한 이유가 다른 파일에서 접근을 못하게 하려고 한 부분인데 @ki960213 는 어떻게 생각하시는지 궁금합니다.

83500e4bb0366e2aebfb85543a322e60e2019eb2

2024-03-26 14:28 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +    companion object {
companion object는 맨 아래 위치 되어야 될 것 같습니다.
수정했습니다.(사실 폴 코드 리뷰를 보고 수정했는데 빠르게 수정했는데 조금 늦었네용 ㅋㅅㅋ;;)

83500e4bb0366e2aebfb85543a322e60e2019eb2

2024-03-26 14:28 UTC, yoonchanchoi commented on app/src/main/res/drawable/category_children.xml
> +</selector>
감사합니다. ^^

2024-03-26 14:42 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +        }
처음에는 해당 부분이 UI쪽을 처리해야 된다고 생각하여 dispather.main을 썻지만
이 부분은 추후에 찾아 보고 알게 되었는데요 
lifecycleScope의 경우는 lifecycler.coroutineScope를 찾아 들어가게 되면 해당 default dispatchers가 dispatchers.main.immediate라고 해서 순차적으로 수행된다고 되어있었습니다. 
하지만 해당 dispatcher.main의 경우 해당 dispatcher.main이 여유가 될 때 돈다고 하더군요 그래서 좋지 못한 코드인거 같습니다. 
또한 말씀대로 현재 상황에서는 selectab에 코루틴으로 실행하지 않는 편이 좋은거 같아 그냥 delay로 수정했습니다. 
observe로도 해봤는데 안되더라고요. 
https://issuetracker.google.com/issues/37140935
마지막 댓글에..구글에서 won't fix라고....ㅠㅠ 한거 같아요...

해당 커밋 수정 부분 싱크가 안 맞는거 같아서 사진으로 올립니당...

![1](https://github.com/abloom-AOS/MERY_Android/assets/74814647/afc27a21-a7f9-4dc5-9e5d-00c29f95f78a)

2024-03-26 15:08 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +        private val PAST_TABITEM_POSION by lazy { 11 }
다른 파일에서 접근하지 못하게 해 캡슐화를 한 것은 좋다고 생각합니다.

2024-03-26 15:37 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryAdapter.kt
> +    }
이렇게 어댑터 패턴에 따라서 뷰홀더를 생성하는 것이 처음이라서 맞게 했는지는 모르겟지만 무언가 
인터페이스와 해당 인터페이스 실체 몸체를 구현 할 때와 원래는 비슷한 느낌이네요 ㅎㅎ
한 가지 질문이 있습니다. 이렇게 했을 경우에 정확한 장점이라는 것이 무엇인지 조금 확 와닿지 않는 부분이 있는데 
혹시 설명해주실 수 있나용?

d40c7ec770ccd505082f2bdd9e13170e0e20005d

2024-03-26 15:41 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryAdapter.kt
> +    }
제가 생각한대로 잘 구현하셨어요 👍

2024-03-27 01:10 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaCategory.kt
> +    PAST("past")
createQnaCategory파일을 category 패키지로 이동했습니다.
한 가지 질문이 있습니다.
해당 파일의 이름에 대해서 입니다. 
createQnaFragment와 CategoryFragment에서 둘 다 사용되는  구조이기 때문에 해당 파일의 이름이 createQnaCategory라고 되어 있는데 Categorys로 바꾸는게 더 좋을까용?

77e565e960fedf09578394e334ebf25adfd8b235

2024-03-27 01:22 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/categorytest/CategoryRepository.kt
> +    private fun requestQuestions(): List<Question> = FakeQuestions().questions
추후에 다름 사람이 코드를 보게 될 경우 오해 소지가 생길 수 있기 때문이군요 
명확성을 주는 부분은 유지 보수에서도 중요한 부분인거 같습니다. 
다시 리마인드 시키고 갑니당^^

2024-03-27 01:25 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/categorytest/CategoryRepository.kt
> +    }
수정했습니당

d3c1408a7c98019b0af9714414aebc98adf1ec39

2024-03-27 01:36 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/categorytest/CategoryViewModel.kt
> +        val check = repository.isLoginCheck()
수정했습니다.
동사부터 쓰도록 하겠습니당!

8f53f2c987f925a75d715f03a0848467fa21e01b

2024-03-27 01:36 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/categorytest/FakeQuestions.kt
> +)
감사합니다 ^^

2024-03-27 01:38 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryAdapter.kt
> +    }
폴과 토마스가 말씀해주신 대로 수정했습니당^^

4e33ad46baac4ad81f829f6377051ceb2078f121

2024-03-27 01:43 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +    private val viewModel: CategoryViewModel by viewModels()
혹시 현재도 반영이 안되어 있는지 확인 해주실 수 있을까용?
해당 부분의 커밋기록이 안보이네용 ㅠㅠ
그래서 일단 사진으로 보여드립니다.

![1](https://github.com/abloom-AOS/MERY_Android/assets/74814647/4270ef86-c85c-4d5b-b5a4-8a3e6e88586f)

2024-03-27 01:45 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +            }
감사합니다.
해당 부분 조금 궁금한 점이 있어서 리뷰 후에 따로 comment로 태그 달아서 두분께 물어보겠습니당!!!

2024-03-27 01:48 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/categorytest/CategoryViewModel.kt
> +        val check = repository.isLoginCheck()
is도 동사입니다. 죄송합니다. 폴의 리뷰가 `isLoginCheck` 대신 `loginCheck`라는 함수명을 쓰라고 한 건 줄 알았는데 변수명이군요.

2024-03-27 01:55 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
>          binding.appbarCategory.setOnNavigationClick {
수정했습니다.
해당 Listener를 발견 못 했었네요 찾아 주셔서 감사합니다 :)

9da0b23d2526e491c8946bf9664cefc67cb4d41c

2024-03-27 02:05 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/categorytest/CategoryViewModel.kt
> +        val check = repository.isLoginCheck()
아 저도 착각했네용 
폴이 말씀하신 부분 부터 수정했습니당^^

50055d13bed84f02a56a5239423ff3e8e8179f30

혹시 그렇다면 @ki960213 해당 함수의 함수명은 어떤게 하는게 맞다고 생각하시나용?
isCheckLogin이 맞을까용? 둘다 동사여서...아니면 다른 방법이 있을까용?

2024-03-27 02:13 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +        lifecycleScope.launch {
혹시 어떤 식으로 메소드를 처리하시라는 건지 여쭈어봐도 될까요?
 메소드 안에 있는
 ```
lifecycleScope.launch {
            binding.tb.selectTab(binding.tb.getTabAt(index))
            delay(100)
            binding.tb.setScrollPosition(index, 0f, false)
        }
        viewModel.requestQuestion(category)
 ```
 해당 부분을 따로 메소드로 한번 더 빼서 호출하라는 말씀인가용?

2024-03-27 02:24 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaCategory.kt
> +    PAST("past")
CategoryFragment 화면에 진입할 때 필요한 인자의 타입을 나타내는 이름을 사용하면 좋아요 😊

2024-03-27 04:05 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +        }
```kotlin
lifecycleScope.launch(Dispatchers.Main) {
    binding.tb.setScrollPosition(...)
}
```
디스패처를 `Dispatchers.Main`으로 설정함으로써 위 코루틴의 실행 시점이 항상 스크롤 할 수 있는 시점 이후가 된다면 `delay()` 대신 디스패처를 변경하는 것도 괜찮은 것 같아요. 확실친 않아서 문제죠... 😓 
정확하진 않지만 `selectTab()`을 호출하면 무언가 비동기적으로 수행되는 어떤 로직이 있고, 그 로직이 수행되어야만 `setScrollPosition()`이 제대로 동작하는 것 같아요. 제 생각엔 이벤트 루프 방식으로 동작하고 이벤트 처리는 선입선출 순서로 수행되므로 디스패처를 `Dispatchers.Main`으로 설정한다면 항상 의도한대로 동작할 것 같긴 합니다.

덕분에 `Dispatchers.Main.immediate`에 대해 알게 되었네요.

2024-03-27 04:35 UTC, leeugun123 requested changes

2024-03-27 04:35 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +    private val viewModel: CategoryViewModel by viewModels()
지금 사진과 커밋 기록 상으로는 변수명이 categoryViewModel이 아닌 viewModel로 되어있습니다.

2024-03-27 04:35 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +        lifecycleScope.launch {
private fun 함수명(){
        lifecycleScope.launch {
                 binding.tb.selectTab(binding.tb.getTabAt(index))
                 delay(100)
                 binding.tb.setScrollPosition(index, 0f, false)
        }
} 
이런식으로 메소드를 따로 분리하여 만약 해당 부분이 다른 부분에서 재사용 될 경우 가독성을 높이기 위함 입니다.

2024-03-27 06:01 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +    private val viewModel: CategoryViewModel by viewModels()
아하 죄송합니다.  착각했네요.
수정했습니다.

9da0b23d2526e491c8946bf9664cefc67cb4d41c

2024-03-27 06:01 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaCategory.kt
> +    PAST("past")
CategoryArgs로 이름 수정했습니다.

82009af9b6b0a4767010567b946ef5116222928f

2024-03-27 07:35 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryRecyclerListener.kt
> +}
수정 했습니다.
오늘 함수를 매개변수로 참조하는 법은 오늘 블로그에 꼭 남겨야겠습니다.

d8e4cc866a42f2a0cbd42333f136cc03a8474a4f

2024-03-27 07:35 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryViewHolder.kt
> +        }
감사합니다. 
오늘도 배웁니다. 늘 Interface를 썼기 때문에 아에 생각도 하지 못했습니다.

0c7e9260c234f7b1dc6dee4d85527fb1f3997ee1

2024-03-27 07:35 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +    }
오타 자주 발생할 수 있는 부분에서 CategoryArgs가 조금 더 좋은 방법인 것 같습니다.

ff6400195ea6f42b8643c2331ccbba587d3d497d

2024-03-27 07:35 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +    private fun initListener() {
해당 부분은 setup으로 쓰겠습니다. 앞으로
init 같은 경우 이미 내장 경우가 있어 헷갈릴 수 있으므로 setup으로 통일하겠습니다.

fd94f77f3117cd241ab7e01c2d8d962a60c51ee9

2024-03-27 07:35 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +        lifecycleScope.launch {
조금 생각을 해봤습니다.
해당 부분의 기능이 처음 카테고리의 스크롤과 보여줄 데이터를 결정하는 것이라고 생각합니다.
그렇기 때문에 함수를 다시 분할하게 되면 오히려 다른 기능으로 인식하여 의미 전달이 잘 안 될 수 있다고 생각합니다.  그렇기 때문에 아래와 같이 수정했습니다.

e576027bed9318b061c343235f0c847e81e41943

2024-03-27 07:35 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +        }
https://jisungbin.medium.com/dispatchers-main-immediate-%EC%9D%98-%EB%8C%80%ED%95%9C-%EC%9D%B4%ED%95%B4-9f073be21e5a
혹시 몰라서 다시 찾아보았습니다.

개인 적인 생각으로는 현재 상황에서는 main을 쓰는게 맞다고 결정했습니다.
말씀하신대로 `dispatchers.Main.immediate`의 경우 이미 메인에 있어 코루틴을 쓰지 않은 것과 같다면 해당 코루틴을 쓰는 이유가 없다고 생각하고 무엇보다 delay를 임의대로 주어야 된다는 부분이 조금 많이 거슬리는 것 같습니다.
물론 해당 부분 main 스레드에서 문제가 생기면 어쩔 수 없이 delay를 주는 방식을 선택해야 될 수도 있지만 현재 그런 문제가 발생하지 않으므로 `Dispatchers.Main`를 사용하기로 했습니다.

추가적으로 개인 판단이 중요하다는 걸 잊고 있었네요^^ 코드리뷰 하다 보니 감사합니다.!

2024-03-27 07:50 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/category/CategoryFragment.kt
> +        viewModel.requestQuestion(category)
[해당부분](https://jisungbin.medium.com/dispatchers-main-immediate-%EC%9D%98-%EB%8C%80%ED%95%9C-%EC%9D%B4%ED%95%B4-9f073be21e5a)
위에 블로그 글을 읽어 보니깐 lifescope의 기본 값은 그냥 코루틴을 안 사용한 것과 비슷하더라고요 
그래서 해당 `Dispatchers.Main`으로 수정했고 말씀하신 대로 어떻게 보면 2가지 기능에 관해 수정을 해야되는 부분일 수도 있다고 생각했지만 해당 메소드에서 나타내고자 하는 것이 처음 seleced된 tabItem을 표시 해줌과 동시에 데이터를 보여주는 것이므로 함수를 나누게 된다면 추후에 다시 보게 될 때 오해의 소지가 생길 수 있다고 생각하여 아래 처럼 수정했습니다. 대신 말씀하신 대로 코루틴을 똑같은 `Dispatcher 스레드`로 나누는 것은 아니라고 판단했습니당^^

감사합니당!!

e576027bed9318b061c343235f0c847e81e41943

2024-03-27 17:24 UTC, ki960213 approved these changes
리뷰 반영하느라 고생하셨습니다 😄

2024-03-28 01:19 UTC, leeugun123 approved these changes

2024-03-28 01:20 UTC, leeugun123 commented
리뷰 반영하시고 수정 하시느라 고생 많으셨습니다.  궁금한게 생길때마다 즉각적으로 물어보시고 고민하시는 모습 보며 많이 배우게 됩니다.

2024-03-28 13:30 UTC, merged