[Feature/41] 회원가입 Step3 이름입력 UI 구현
ABloom-AOS/Merry_Android pull request #42
Opened 2024-03-27 08:50 UTC by leeugun123

#### close #41 

### ✏️ 개요

회원가입 Step3 이름입력 UI 구현

### 💻 작업 사항

1. 회원가입 Step2(결혼날짜 선택) Spinner DatePicker UI 적용
2. 회원가입 Step3(이름 입력) UI 구현
3. 각 회원가입 프래그먼트 viewModel를 사용한 정보 유지

### 📄 리뷰 노트

sharedViewModel를 사용하여 이전에 있던 정보가 계속 유지되도록 구현하였습니다.(이름은 회원가입에 맞는 viewModel로 수정하겠습니다.)
뷰모델과 각 프래그먼트의 상호작용을 중점적으로 보시면 되겠습니다.

+추가적으로 Material Design으로 EditText를 구현하였는데 hint 부분이 label로 대체되는 문제가 발생했습니다.
  이 부분에 대해 라벨의 문구를 변경하는 등의 수정이 필요 할 것 같습니다.

### 📱결과 화면(optional)

<img width="374" alt="Screenshot 2024-03-27 at 5 38 42 PM" src="https://github.com/abloom-AOS/MERY_Android/assets/50404123/1a04caf0-cb07-4c64-9086-82286780a3fd">

<img width="373" alt="Screenshot 2024-03-27 at 5 39 23 PM" src="https://github.com/abloom-AOS/MERY_Android/assets/50404123/a596dc8d-9aa1-4876-9d0c-19ec93743797">
<img width="371" alt="Screenshot 2024-03-27 at 5 40 08 PM" src="https://github.com/abloom-AOS/MERY_Android/assets/50404123/4affff96-5d68-4ca5-a1cc-e21d1e5cb21d">

2024-03-27 09:16 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/MarryDate.kt
> +)
파이어베이스를 보니 년/월/일 뿐만 아니라 시/분/초까지 정보가 들어있는데 시/분/초까지 구현하면 불필요한 코드가 생길 것 같아 
임시적으로 년/월/일로만 데이터를 구성하였습니다.

2024-03-27 09:16 UTC, leeugun123 commented on app/src/main/res/layout/fragment_marry_date.xml
> +            android:layout_height="200dp"
해당 피그마 디자인이 수정되어 정확한 Height 값을 알지 못해 임시적으로 200dp로 설정하였습니다.

2024-03-27 09:37 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/InputNameFragment.kt
> +        binding.inputNameEditText.addTextChangedListener(object : TextWatcher {
사용되지 않는 override 부분은 확장 함수를 이용해서 사용하는 부분만 남기는 것도 좋을 것 같습니다.
꼭 그렇게 하시지 않으셔도 됩니다.  예시는 
```
fun TabLayout.onTabSelected(onTabSelected:(tab: TabLayout.Tab) -> Unit){
    this.addOnTabSelectedListener(object: TabLayout.OnTabSelectedListener{
        override fun onTabSelected(tab: TabLayout.Tab) {
            onTabSelected(tab)
        }

        override fun onTabUnselected(tab: TabLayout.Tab?) {}

        override fun onTabReselected(tab: TabLayout.Tab?) {}
    })
}

```
이런 느낌입니다.

2024-03-27 09:37 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/MarryDateFragment.kt
> +    private val sharedViewModel: SharedViewModel by activityViewModels()
viewModel 공유해서 사용하시는 부분 좋은 것 같습니다.!!^^

2024-03-27 09:37 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
>      companion object {
캡슐화 잘해주셨네용^^

2024-03-27 09:38 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/InputNameFragment.kt
> +        binding.inputNameEditText.addTextChangedListener(object : TextWatcher {
해당부분을 저는 다른 클래스 파일로 뺐습니다. `xxxUtil.kt` 명칭으로요

2024-03-27 18:11 UTC, ki960213 requested changes
가입하기 과정 동안 데이터를 유지하려고 하신 걸 보니 생각을 많이 하신 것 같아요 👍   
몇 가지 코멘트 남겼으니 확인해주세요 😄

2024-03-27 18:11 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/BrideGroomSelectionFragment.kt
> +    private val sharedViewModel: SharedViewModel by activityViewModels()
뷰모델의 범위를 늘려서 데이터를 가입하기 하는 동안 유지하려는 시도 좋았어요 👍    
하지만 `activityViewModels()`를 사용하여 만든 `SharedViewModel` 객체는 프래그먼트를 관리하는 액티비티가 완전히 제거되기 전까지 살아있습니다. 그리고 앱 로직을 보면 `SharedViewModel`에서 관리하는 데이터는 가입하기를 하는 동안만 필요하죠. 따라서 불필요하게 메모리를 점유합니다. 이럴 때 사용하기에 좋은 범위가 있습니다. 바로 [탐색 그래프로 범위가 지정된 뷰모델](https://developer.android.com/topic/libraries/architecture/viewmodel/viewmodel-apis?hl=ko#vm-api-navgraph)입니다.    
제가 새로 PR 올린 코드에 이 상황에 필요한 뷰모델도 전부 구현되어있으니 제 PR을 approve 하고 그것을 사용해주세요 😊

2024-03-27 18:11 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/BrideGroomSelectionFragment.kt
>          }
`setSex(true)`를 보면 남자가 true인지 여자가 true인지 알 수 없습니다. 보통 이런 경우 enum class를 사용하여 명확하게 하는 게 좋다고 생각합니다. 하지만 이것도 제가 PR 올린 코드를 사용한다면 쉽게 해결할 수 있을 거예요.

2024-03-27 18:11 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/InputNameFragment.kt
> +    }
이 부분은 [양방향 데이터 바인딩](https://developer.android.com/topic/libraries/data-binding/two-way?hl=ko)을 사용하면 매우 쉽게 처리할 수 있어요. 이것도 새로 만든 PR의 코드를 사용하면 쉽게 구현하실 수 있을 거에요 😊

2024-03-27 18:11 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/InputNameFragment.kt
> +        if (sharedViewModel.staticName != NULL_STRING)
`NULL_STRING`의 값을 보니 "null" 문자열이더군요. 아마 `sharedViewModel.stateName.isBlank()`를 의도하신 것 같은데 맞나요?

2024-03-27 18:11 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/MarryDate.kt
> +)
코틀린에서 시각 표현은 `LocalDate` 혹은 `LocalDateTime` 클래스를 사용하는 게 좋습니다. 시각 관련 유용한 API들이 많기 때문이죠.

2024-03-27 18:11 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SharedViewModel.kt
> +        get() = dynamicMarryDate.value
보통 `LiveData`를 사용할 땐 아래처럼 코드를 작성합니다.
```kotlin
private val _name = MutableLiveData<String>()
val name: LiveData<String> = _name

private val _marryDate = MutableLiveData<MarryDate>()
val marryDate: LiveData<MarryDate> = _marryDate
```
이런 식으로 백킹 프로퍼티만 변할 수 있게 허용하고 public 프로퍼티는 불변 `LiveData`로 선언한 뒤 
```kotlin
viewModel.marryDate.observe(viewLifecycleOwner) { ... }
```
이러한 코드로 marryDate가 변경될 때마다 수행될 로직을 정의합니다. 이것도 새 PR에 제가 Flow로 만들어 놓았으니 그걸로 사용해주시면 감사하겠습니다 😄 

참고로 `dynamicXxx`, `staticXxx` 같은 타입을 의미하는 네이밍은 좋지 않습니다. 변수의 네이밍이 자료형에 의해 변경될 수 있기 때문이죠. [참고자료](https://tecoble.techcourse.co.kr/post/2020-04-24-variable_naming/)

---
처음엔 위처럼 생각했지만 다시 보니 일부러 불필요한 연산을 줄이기 위해 화면에 진입했을 때 한 번만 값을 불러오도록 하기 위해 위처럼 선언한 것이군요 👍

2024-03-27 18:11 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
>      }
데이터 바인딩을 사용하면 이 5줄 없애고 한줄로 만들 수 있습니다!

2024-03-28 00:40 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/BrideGroomSelectionFragment.kt
> +    private val sharedViewModel: SharedViewModel by activityViewModels()
저도 메모리 누수에 대한 문제는 고려하고 있었는데 activityViewModels() 말고는 
도저히 구현 할 방법을 찾지 못해서 사용했습니다.ㅠㅠ 
탐색 그래프로 범위가 지정되는 뷰모델이 있는 줄 처음 알았네요!!  토마스가 만들어주신 뷰모델 참고해서 수정하겠습니다.

2024-03-28 00:40 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/BrideGroomSelectionFragment.kt
>          }
저도 구현할때 자료형이 Boolean이라 남자/여자 선택하는 것이 조금 애매하다고 느꼈는데 
이 부분에 대해 enum class를 만드셨군요..!! 토마스 PR 이용하여 수정하겠습니다!
ce8be8403480e05eb4ffafa0e89b165ea24f5a0f

2024-03-28 00:40 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/InputNameFragment.kt
> +    }
넵 만드신 PR 이용하여 수정하였습니다!
de705efa1c7c48a198c1d192f35821af284ee7ec

2024-03-28 00:40 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/MarryDate.kt
> +)
LocalDate를 고려하지 못했네요.. 해당 클래스를 사용하여 수정하겠습니다.

2024-03-28 00:40 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SharedViewModel.kt
> +        get() = dynamicMarryDate.value
아무래도 말씀해주신 LiveData로 선언할 경우, 한번만 값을 불러오는 로직과 달리 값이 업데이트될 때마다 값을 불러들이기 때문에 LiveData가 아닌 일반적인 자료형으로 선언하고, 이를 구분하기위해 static으로 변수명을 지었습니다.

2024-03-28 00:40 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
>      }
데이터 바인딩을 사용하는 것이 아직 미숙하네요.. 데이터바인딩을 사용하여 구현하겠습니다.

2024-03-28 01:01 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/InputNameFragment.kt
> +        if (sharedViewModel.staticName != NULL_STRING)
처음 구현 시 if(sharedViewModel.staticName != null)로 했는데도 데이터가 업데이트가 되지 않아 확인해보니
sharedViewModel.staticName이 아직 초기화가 안됐을때는 null이 아닌 문자열 "null"로 읽히더라고요. 
따라서 문자열 "null"을 상수로 처리하여 구현하였습니다. 

+ sharedViewModel.stateName.isNotBlank()도 마찬가지로 초기 화면 진입시 sharedViewModel.staticName에 처음 문자열 "null"이 저장되니 문자열이 있는 것으로 판단하여 EditText에 문자열 "null"이 적용되는 문제가 발생하였습니다.

2024-03-28 01:07 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/InputNameFragment.kt
> +        binding.inputNameEditText.addTextChangedListener(object : TextWatcher {
```kotlin
  private fun initListener() {
        binding.inputNameEditText.addTextChangedListener(afterTextChanged = { s ->
            sharedViewModel.setName(s.toString())
        })
    }

```
이런식으로 사용하는 것도 괜찮을까요?

2024-03-28 02:12 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/InputNameFragment.kt
> +        binding.inputNameEditText.addTextChangedListener(object : TextWatcher {
제가 만든 뷰모델과 양방향 데이터 바인딩을 사용한다면 만들 필요없습니다 😊

2024-03-28 02:21 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/InputNameFragment.kt
> +        if (sharedViewModel.staticName != NULL_STRING)
null에 `toString()` 함수를 사용하면 "null" 문자열이 반환되는군요...   
양방향 데이터 바인딩 사용해주세요 😢

2024-03-28 02:23 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SharedViewModel.kt
> +        get() = dynamicMarryDate.value
값을 관찰하는 게 아니라 특정 시점에 요청만 할 목적이라면 아래의 코드도 괜찮을 것 같아요.
```kotlin
var name: String = ""
    private set
```

2024-03-28 08:14 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    private val signUpViewModel: SignUpViewModel by activityViewModels()
InputNameFragment의 editText의 내용을 서로 공유하기 위해 activityViewModels()로 초기화 하였습니다. 
더 좋은 방법이 있다면 가르쳐주시면 감사하겠습니다.

2024-03-28 09:32 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/InputNameFragment.kt
> +        binding.inputNameEditText.addTextChangedListener(object : TextWatcher {
de705efa1c7c48a198c1d192f35821af284ee7ec
수정하였습니다.

2024-03-28 09:33 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/BrideGroomSelectionFragment.kt
> +    private val sharedViewModel: SharedViewModel by activityViewModels()
ce8be8403480e05eb4ffafa0e89b165ea24f5a0f 
수정하였습니다.

2024-03-28 09:34 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/InputNameFragment.kt
> +        if (sharedViewModel.staticName != NULL_STRING)
de705efa1c7c48a198c1d192f35821af284ee7ec 
수정하였습니다.

2024-03-28 09:35 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
>      }
de705efa1c7c48a198c1d192f35821af284ee7ec
실수로 SignUpFragment에 적용하는 커밋을 남겨두지는 못했네요.. 
데이터 바인딩을 이용하여 수정하였습니다.

2024-03-28 15:26 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    private var curStep = STEP_BRIDE_GROOM_SELECTION
childFragmentManager가 현재 어떤 프래그먼트를 가리키고 있는지의 대한 코드를 아직 구현하지 못하였습니다.
따라서 curStep으로 처리하였는데 이럴 경우 문제가 생기기 때문에 이 부분에 대해 좀 더 자료를 찾아본후 구현하겠습니다.
더 좋은 방법이 있다면 피드백 주시면 감사하겠습니다.

2024-03-29 03:22 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/InputNameFragment.kt
> +        binding.inputNameEditText.addTextChangedListener(object : TextWatcher {
이번에 문답관련 UI 짤때 사용해봐야겠습니당!
엄청 좋네요

2024-03-29 05:34 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    private var curStep = STEP_BRIDE_GROOM_SELECTION
https://developer.android.com/guide/fragments/fragmentmanager?hl=ko
프래그먼트 매니저 공식문서 자료입니다. `childFragmentManager`와 `parentFragmentManager`, `supportFragmentManager`에 대해 알 수 있을 거예요. 😊

2024-03-29 05:36 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    private var curStep = STEP_BRIDE_GROOM_SELECTION
참고로 `curStep`을 프래그먼트의 멤버 변수로 선언하면 발생하는 문제는 이전 코드 리뷰에서 언급했으니 링크를 드릴게요. https://github.com/abloom-AOS/MERY_Android/pull/37#discussion_r1537483939

2024-03-29 06:10 UTC, ki960213 requested changes
현재 아쉬운 점이 2가지 있습니다.
- 뒤로 버튼 클릭 시 바로 홈 화면으로 감
- 이름 작성 후 뒤로 갔다가 다시 이름 입력 화면으로 이동하면 이름이 있음에도 다음 버튼이 비활성화 되어 있음

위 문제를 해결하려면 프래그먼트의 백 스택과 데이터 바인딩을 적절히 사용해야 해요. 혹시 어려울 것 같다면 제가 하겠습니다. 로그인 기능 먼저 해주세요. 😢

2024-03-29 06:10 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/BrideGroomSelectionFragment.kt
> +    }
이렇게 하면 성별 선택 화면에 진입했을 때만 배경을 그려주네요. 그리고 지금은 프래그먼트를 전환할 때마다 뷰가 제거됐다가 다시 생기니까 성별을 선택해서 배경이 바뀐 게 남지 않고 다시 선택 안된 배경을 그려주는데, 만약 프래그먼트를 `replace`가 아닌 `add` 방식으로 했다면 둘 다 선택될 수 도 있을거에요. 따라서 문제를 정확히 해결한 코드를 보여드리자면 아래와 같습니다.
```kotlin
repeatOnStarted {
    viewModel.selectedSex.collect {
        when (it) {
            Sex.MALE -> {
                binding.groomBut.setBackgroundResource(R.drawable.signup_gender_selected)
                binding.brideBut.setBackgroundResource(R.drawable.signup_gender_unselected)
            }
            Sex.FEMALE -> {
                binding.groomBut.setBackgroundResource(R.drawable.signup_gender_unselected)
                binding.brideBut.setBackgroundResource(R.drawable.signup_gender_selected)
            }
            null -> {
                binding.groomBut.setBackgroundResource(R.drawable.signup_gender_unselected)
                binding.brideBut.setBackgroundResource(R.drawable.signup_gender_unselected)
            }
        }
    }
}
```
위처럼 선택된 성별이 달라질 때마다 신랑 신부 버튼 둘다 배경을 변경해주어야 합니다. 이것을 데이터 바인딩을 사용한다면 훨씬 쉽게 할 수 있어요.
```kotlin
android:background="@{viewModel.selectedSex == Sex.FEMALE ? @drawable/signup_gender_selected : @drawable/signup_gender_unselected}"
```

2024-03-29 06:10 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/BrideGroomSelectionFragment.kt
> +            .commitNow()
`commitNow()`를 사용하면 백스택에 트랜잭션을 추가할 수 없습니다. 만약 백스택을 사용하고 싶다면 `FragmentManager.executePendingTransactions()` 메서드를 사용하는 게 좋아요.

2024-03-29 06:10 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    private fun observeSignUpFragmentManager() {
뷰모델에서 제공하는 객체를 관찰하는 게 아니라 프래그먼트 매니저에 콜백을 등록하는 데 `observeXxx` 네이밍을 사용하신 이유가 궁금합니다...!

2024-03-29 06:10 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +                            setupForBrideGroomSelection()
프래그먼트가 created 상태가 되었을 때 앱바와 프로그래스 바를 변경해주는 일을 하는 함수가 `setupXxx()`네요. setup은 보통 초기화를 할 때 사용되는 이름이므로 "앱바와 프로그래스 바를 신랑 신부 선택 화면에 맞게 변경한다" 라는 뜻을 유추할 수 있을만한 이름으로 작성하는 게 좋을 것 같아요.

2024-03-29 06:10 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +                    }
안드로이드 앱은 대부분 R8으로 난독화 및 축소 후 배포를 합니다. R8으로 앱을 축소하면 리플렉션 관련 정보까지 지워질 수 있기 때문에 리플렉션으로 기능을 만드는 것은 이후 런타임 에러가 발생할 가능성이 있습니다.

2024-03-29 07:40 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SharedViewModel.kt
> +        get() = dynamicMarryDate.value
저도 사실 LiveData를 저런 식으로 사용했는데 앞으로는 고쳐야겠습니당

2024-03-29 10:20 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/BrideGroomSelectionFragment.kt
> +    }
데이터 바인딩과 삼항 연산자를 통해서 이렇게 간단히 표현 될 수 있었네요..
Xml에서 ViewModel에 데이터를 반영하는 부분만 알고 있었는데 
이렇게 if else문으로 drawable를 적용 할 수 있는 부분은 미처 생각하지 못했습니다.

2024-03-29 10:20 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/BrideGroomSelectionFragment.kt
> +    }
다음에 구현할때는 일단 Fragment에서 코드를 구현하는 것이 아닌 바인딩을 적용하는 것부터 고려하여 개발 해야겠습니다.

2024-03-29 10:20 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/BrideGroomSelectionFragment.kt
> +            .commitNow()
[프래그먼트 백스택의 이해 ](https://medium.com/shdev/fragment-back-stack%EC%9D%98-%EC%9D%B4%ED%95%B4-ed30638a57f1)
일단 백스택을 사용할 일이 없어서 commitNow를 사용하긴 했는데 
백스택을 사용하는 이유에 대해서 알 수 있을까요?

2024-03-29 10:20 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/BrideGroomSelectionFragment.kt
> +            .commitNow()
혹시 백스택에 트랜잭션을 추가하는 이유가 이전단계로 되돌아 가는 작업을 구현하기 위해서인가요?

[프래그먼트 백스택의 이해](https://medium.com/shdev/fragment-back-stack%EC%9D%98-%EC%9D%B4%ED%95%B4-ed30638a57f1)
해당 개념에 대해 잘 정리되어 있어 공유합니다.

2024-03-29 10:20 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    private fun observeSignUpFragmentManager() {
observed의 개념과 콜백을 등록하는 개념이 혼동되어 observe를 붙여 사용한 것 같습니다.
initFragmentSpecificSetup()은 어떻게 생각하시나요?

2024-03-29 10:20 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +                            setupForBrideGroomSelection()
updateAppBarAndProgressForBrideGroomSelection()은 어떠신가요?

2024-03-29 10:22 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/BrideGroomSelectionFragment.kt
> +            .commitNow()
뒤로 버튼을 눌렀을 때 가입하기 화면 전체가 닫히는 게 아니라 이전 단계로 되돌아가야 합니다. 이때 백 스택을 사용하면 좋다고 생각했습니다.

2024-03-29 10:23 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    private fun observeSignUpFragmentManager() {
프래그먼트 매니저를 초기화하는 것이므로 `initSignUpFragmentManager()` 혹은 `setupSignUpFragmentManager()`가 더 어울린다고 생각합니다.

2024-03-29 10:26 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +                            setupForBrideGroomSelection()
"신랑 신부 선택 화면의 앱바와 프로그래스 바"를 줄여서 BrideGroomUi라고 부르고 `changeToBrideGroomUi()`는 어떠신가요? 이름이 명확한 것도 좋지만 너무 길면 오히려 가독성이 떨어지기 때문에 의미를 함축한 언어를 사용하여 네이밍 하는 것도 방법이라고 생각해요. 😊

2024-03-29 10:53 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +                    }
배포 시 난독화 및 축소로 인해 필요한 정보까지 지워질 수 있는 문제가 발생할수도 있군요..

2024-03-29 10:58 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +                            setupForBrideGroomSelection()
좋은 네이밍 인 것 같습니다. 명확하지만 이름이 길 경우, 가독성이 떨어질 가능성이 있겠네요.
이를 고려해서 개발할때 명확한 이름을 짓는 것에 좀 더 신경쓰겠습니다.

2024-03-29 11:00 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +                    }
좋습니다! 저 태그들은 프래그먼트가 존재해야만 사용하는 의미가 있으므로 각 프래그먼트의 companion object가 상수로  가지고 있도록 하면 더 좋을 것 같습니다.

`const val TAG = "TAG_INPUT_NAME_FRAGMENT"`
`InputNameFragment.TAG` 이런 식으로 사용할 수 있게요...!

2024-03-29 11:07 UTC, leeugun123 commented
토마스 덕분에 프래그먼트 트랜잭션에 대해서 많이 공부 할 수 있는 기회를 가진 것 같습니다.
해당 PR은 토마스가 회원가입 기능을 구현하실때까지 그대로 두고, 로그인 기능 UI 먼저 개발하겠습니다.

2024-03-29 12:13 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +                    }
앱 배포 중에 축소로 지워진다는 애기를 들어본 적 있었는데 이번에 조금 더 알고 가는거 같습니당^^

2024-03-29 14:25 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/BrideGroomSelectionFragment.kt
> +    }
저도 많이 느끼는 부분이 Databinding을 쓸 때 구조적인 생각을 더해야되는 부분이 있지만 대신 잘만 설계하게 된다면 해당 부분에서 request(), Observer에 대한 코드가 없어집니다. 이 점이 제일 놀라운 부분인거 같습니다. 바로 ViewModel의 type을 연결해서 데이터를 넣고 반응된다는 점이 제일 신기합니다.^^

2024-03-30 06:01 UTC, ki960213 approved these changes
아직 InputName 화면에 진입했을 때 사용자의 이름이 입력되어 있음에도 불구하고 액션 버튼이 비활성화되는 문제가 있긴 하지만, 일단은 넘어가도 좋을 것 같습니다. 😊 
고생하셨습니다 👍

2024-03-30 06:01 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/BrideGroomSelectionFragment.kt
> +            signUpViewModel.selectSex(Sex.MALE)
뷰모델과 데이터 바인딩을 잘 사용해주셨군요 👍

2024-03-30 06:01 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/BrideGroomSelectionFragment.kt
> +        }
많은 곳에서 이 로직과 비슷한 로직이 사용되고 있습니다. 중복을 없앨 수 있지만 시간이 없으니 다음에 변경해도 괜찮습니다 😊 
그리고 fade_in, fade_out 애니메이션은 안드로이드에서 기본적으로 제공하는 리소스입니다. 따라서
`setCustomAnimations(android.R.anim.fade_in, android.R.anim.fade_out, android.R.anim.fade_in, android.R.anim.fade_out)`
이렇게 사용할 수 있습니다.

2024-03-30 06:01 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/SignUpFragment.kt
> +    }
`onBackPressedDispatcher`를 잘 사용해주셨군요 👍

2024-03-30 06:01 UTC, ki960213 commented on app/src/main/res/layout/fragment_bride_groom_selection.xml
> +            android:background="@{viewModel.selectedSex == SEX.MALE ? @drawable/signup_gender_selected : @drawable/signup_gender_unselected}"
👍

2024-03-30 06:01 UTC, ki960213 commented on app/src/main/res/layout/fragment_input_name.xml
> +                android:text="@={viewModel.name}" />
양방향 데이터 바인딩 👍

2024-03-30 06:01 UTC, ki960213 commented on app/src/main/res/layout/fragment_sign_up.xml
> +            app:isActionEnabled="@{!viewModel.name.blank}"
정확히는 현재 InputName 화면이 아니거나 사용자가 입력한 이름이 비어있지 않을 때 액션 버튼이 활성화 되어야겠죠? 😓

2024-03-30 06:05 UTC, leeugun123 commented
> 아직 InputName 화면에 진입했을 때 사용자의 이름이 입력되어 있음에도 불구하고 액션 버튼이 비활성화되는 문제가 있긴 하지만, 일단은 넘어가도 좋을 것 같습니다. 😊 고생하셨습니다 👍

추가적으로 프로그래스바 애니메이션도 구현하였습니다.

2024-03-30 07:53 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_input_name.xml
> +                android:text="@={viewModel.name}" />
양방향 데이터 바인딩 진짜 좋네요 일단 linstener3개가 없어진다는게 제일 놀랍네요.

2024-03-30 07:53 UTC, yoonchanchoi approved these changes

2024-03-30 08:29 UTC, leeugun123 commented on app/src/main/java/com/abloom/mery/presentation/ui/signup/BrideGroomSelectionFragment.kt
> +        }
기본적으로 제공되는 리소스였군요.. 정보 감사합니다.

2024-03-30 08:33 UTC, merged