[Feature/#59] 오늘의 추천 질문 기능 개발
ABloom-AOS/Merry_Android pull request #64
Opened 2024-04-01 01:48 UTC by yoonchanchoi

#### close #59

### ✏️ 개요

오늘의 추천 질문 기능 개발

### 💻 작업 사항

오늘의 추천 질문 기능 개발

### 📄 리뷰 노트

오늘의 추천 질문 기능 개발

### 📱결과 화면(optional)

<img src="https://github.com/abloom-AOS/MERY_Android/assets/74814647/6e925250-7ffe-4355-b787-dd22a1bdee0f" width="200" height="400">
<img src="https://github.com/abloom-AOS/MERY_Android/assets/74814647/f1e45b60-5d7f-46fe-b954-8e39eb7f68a1" width="200" height="400">
<img src="https://github.com/abloom-AOS/MERY_Android/assets/74814647/c317af09-1fc1-4101-9030-acb3345a430a" width="200" height="400">

### 📚 ETC(optional)

오늘의 추천 로직 부분에서 처음에는 리스너 부분도 Databinding에 적용했었지만 로직이 조금 길어져 일단 Fragment 코드단에서 처리 하도록 했습니다.ㅠㅠ

추가적으로 null값일 들어오는 경우는 값이 없다는 text 메시지를 보여주고 클릭이 안되게 했습니다. null일 경우 더 좋은 방법이 있다면 알려주세요

마지막으로 토마스가 말씀하신 대로 비로그인 상태일 때 메인 뷰 모델을 가져와서 로그인 이벤트 발생 함수를 호출하도록 했습니다. 이 부분에서 로그인 및 비로그인 상태 값을 가져와야 된다고 생각해서 CreateQnaViewModel에 isLogin을 가져오는 코드를 추가했습니다. 해당 부분 잘못된 부분이 있다면 알려주세용

2024-04-01 05:40 UTC, ki960213 requested changes
코드가 짧아서 리뷰하기 변했어요! 
리뷰를 하면서 궁금한 게 있습니다. 혹시 저희 로그인하지 않은 상태에서는 오늘의 질문을 보여주지 않아야 하는 것인가요?

2024-04-01 05:40 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
> +            }
`Flow`에서 `collect`는 `LiveData`의 `observe`와 역할이 비슷합니다. 위 코드는 `isLogin`의 값이 변경될 때마다 `collect` 블럭 안의 코드를 실행합니다. 
저희가 구현하고 싶은 로직은 오늘의 질문을 클릭했을 때 로그인 되어있지 않다면 로그인 이벤트를 보내고 홈 화면으로 이동하고, 로그인 되어있다면 해당 질문에 대한 답변을 작성하는 화면으로 이동하는 것입니다.
하지만 위 로직은 오늘의 질문을 클릭했을 때, **`isLogin`이 변경될 때마다** `isLogin`의 값이 `true`라면 답변 작성 화면으로 이동하고, `false`라면 로그인 이벤트를 보내고 홈 화면으로 이동하는 로직을 **실행하라고 정의한 것**입니다.
어떻게 코드를 변경해야 문제를 해결할 수 있을까요? 참고로 `Flow`에서 값을 단순히 조회하는 방법은 `LiveData`와 같습니다.

2024-04-01 05:40 UTC, ki960213 commented on app/src/main/res/layout/fragment_create_qna.xml
> +                        android:text="@{viewModel.isLogin == true ? (viewModel.todayRecommendationQuestion.content == null ? @string/createqna_blank_todayRecommendationQuestion : viewModel.todayRecom
로그인 하지 않았다면 essential 질문 중 하나를 랜덤으로 보여주는 게 아니라 로그인 해달라는 문자열을 보여주는 건가요?
![image](https://github.com/abloom-AOS/MERY_Android/assets/123928686/183dbd84-152b-4769-91c5-b0865d0ac005)

2024-04-01 12:34 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
> +            }
아하 오늘 한 가지 배우고 갑니다.
말씀대로 저희가 원하는 것은 리스너를 눌렸을 때 해당 로그인 상태와 비로그인 상태에 따른 버튼 이벤트의 차이점입니다. 하지만 제가 구현했던 코드는 그저 isLogin이 변경될 때마다 이벤트를 보내주는 것이더군요. 
늘 좋은 리뷰 감사합니다.

그래서 일단 isLogin을 받는 값을 따로 지정해서 로그인 값을 Fragment에서 받고 해당 버튼이 클릭 되었을 때 해당 LoginFlag에 따라서 이벤트가 다르게 해주었습니다. 하지만 조금 무언가 더 좋은 코드가 있을 거 같기도 합니다. 혹시 있을까요? 😁

90d6e50b427ace2d8947fe53cbda9e0116f09fec

2024-04-01 12:41 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_create_qna.xml
> +                        android:text="@{viewModel.isLogin == true ? (viewModel.todayRecommendationQuestion.content == null ? @string/createqna_blank_todayRecommendationQuestion : viewModel.todayRecom
이 부분은 제가 너무 많이 생각하다가 원하는 요청 사항에서 벗어났던 것 같습니다.
감사합니다.👍
아래처럼 수정했습니다.^^

b19e8d2b58c46d2a5fd0cbcfc03d64d00a623518

2024-04-01 13:57 UTC, ki960213 requested changes
아픈 몸을 이끌고 개발하시느라 고생하시는 것 같아요 😢 
천천히 해주셔도 괜찮습니다 👍

2024-04-01 13:57 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
> +                        createQnaViewModel.todayRecommendationQuestion.filterNotNull().collect {
`collect`가 실행되면 flow가 실행되고 이후 변화를 감지할 수 있습니다. `LiveData`처럼요. 저희가 하고싶은 일은 오늘의 질문 클릭 시 다른 화면으로 이동하는 것입니다. 변화를 감지하는 것을 시작하는 게 아닙니다. 😊

2024-04-01 13:57 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
> +            when (loginFlag) {
`loginFlag` 멤버 변수를 만들 필요 없이 `LiveData`처럼 `viewModel.isLogin.value`로 값을 조회하면 됩니다. :)

2024-04-01 13:57 UTC, ki960213 commented on app/src/main/res/layout/fragment_create_qna.xml
> +                        android:text="@{viewModel.todayRecommendationQuestion.content == null ? @string/createqna_blank_todayRecommendationQuestion : viewModel.todayRecommendationQuestion.content}"
만약 오늘의 질문이 없을 때 "오늘의 추천 질문은 없습니다."라는 문자열을 보여준다면, 네트워크 상황이 좋지 않아서 오늘의 질문을 불러오는 게 느릴 때 사용자는 "오늘의 추천 질문은 없습니다."라는 문자열을 보다가 로딩이 끝나면 오늘의 질문을 보게 될 것입니다. 그냥 빈 문자열을 보여주는 게 낫지 않을까요? 그래서 저는 null 처리를 하지 않아도 된다고 생각합니다. 😄

2024-04-01 14:42 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
> +            when (loginFlag) {
수정했습니다.
위에 리뷰에서 이어지는 부분이여서 같은 커밋 header를 남깁니다.^^
의도하신 부분이 맞다면 제가 null일 경우에 return으로 처리를 했는데 이 부분도 let으로 처리하는게 맞을지 궁금합니다. 

2ed5f7fae7887fd6d1f14c0c905ded143066f983

2024-04-01 14:42 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
> +                        createQnaViewModel.todayRecommendationQuestion.filterNotNull().collect {
혹시 의도 하신 부분이 아래 수정한 부분일까용?
이벤트 클릭 때 감지를 걸어놓는 것이 아니라 그냥 해당 이벤트 발생 시에 ViewModel의 있는 질문의 id값을 가져오는 방법으로 넘기라는 말씀이신건가요?

2ed5f7fae7887fd6d1f14c0c905ded143066f983

2024-04-01 14:42 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_create_qna.xml
> +                        android:text="@{viewModel.todayRecommendationQuestion.content == null ? @string/createqna_blank_todayRecommendationQuestion : viewModel.todayRecommendationQuestion.content}"
로딩 부분까지는 미처 생각지 못했습니다. 
디테일한 부분까지 챙겨주셔서 감사합니다.

91299099f0ccf61dc1bd807779325711410702dc

2024-04-01 15:03 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
> +                        createQnaViewModel.todayRecommendationQuestion.filterNotNull().collect {
넵 맞습니다 :)

2024-04-01 15:04 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
> +            when (loginFlag) {
사실 null 처리는 처음에 검사하고 early return을 하는 게 가독성이 좋다고 생각합니다. 하지만 시간이 없으니 넘어가도 좋을 것 같아요. 😊

2024-04-01 15:21 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
> +            when (loginFlag) {
감사합니다. 배우고 갑니당.^^

2024-04-01 16:31 UTC, ki960213 commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
> +                        createQnaViewModel.todayRecommendationQuestion.filterNotNull().collect {
생각해보니 Flow는 collect해야 Flow가 실행되어서 값을 방출하기 때문에 단순히 value로 조회하면 값이 방출되지 않아 항상 초기값을 가져오네요 😢 죄송합니다. `last()` 같은 collect 함수로 값을 조회해야 할 것 같네요.

2024-04-01 17:12 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
> +                        createQnaViewModel.todayRecommendationQuestion.filterNotNull().collect {
그렇군요 괜찮습니다. 
Flow는 첨이라 솔직히 방출이라 그럴 수도 있겠다는 생각이 들기도 했어용 저도 부족했습니당^^
감사합니다. 그럼 제가 바로 collect써서 수정하겠습니당!!
만약에 그렇게 되면 해당 로그인 부분도 이전처럼 flag를 써서 하면 될까용?

2024-04-02 00:34 UTC, yoonchanchoi commented on app/src/main/java/com/abloom/mery/presentation/ui/createqna/CreateQnaFragment.kt
> +                        createQnaViewModel.todayRecommendationQuestion.filterNotNull().collect {
수정했습니다.

965300fdc33e4b64ffaa2305f3d54ba3507011cf

2024-04-02 03:30 UTC, ki960213 approved these changes
구현하시느라 고생하셨습니다 😄

2024-04-02 06:05 UTC, leeugun123 approved these changes

2024-04-02 06:06 UTC, leeugun123 commented
고생 많으셨습니다!!

2024-04-02 07:17 UTC, merged